# Berlin neighborhood clustering – data exploration

This notebook builds and explores a neighborhood-level feature table for Berlin.

It combines:
- amenity counts from SQL
- accessibility signals
- spatial normalization using neighborhood area
- population normalization using population data
- proximity features based on centroid-to-amenity distance

The goal is to prepare a clean feature space for later clustering and neighborhood profiling.

In [1]:
from pathlib import Path
import os
import warnings
from dotenv import load_dotenv

import numpy as np
import pandas as pd
from sqlalchemy import create_engine, text
from sqlalchemy.exc import SQLAlchemyError

warnings.filterwarnings("ignore")

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 200)
pd.set_option("display.max_colwidth", 120)

## Connect to the database

We connect to the local PostgreSQL instance.

The SQL logic is kept in separate `.sql` files so that:
- the notebook stays readable
- SQL can be tested independently
- feature engineering logic is easier to maintain

In [2]:
# Load database credentials from environment variables

load_dotenv()

DB_USER = os.getenv("DB_USER")
DB_PASSWORD = os.getenv("DB_PASSWORD")
DB_HOST = os.getenv("DB_HOST", "localhost")
DB_PORT = os.getenv("DB_PORT", "5433")
DB_NAME = os.getenv("DB_NAME")

engine = create_engine(
    f"postgresql+psycopg2://{DB_USER}:{DB_PASSWORD}@{DB_HOST}:{DB_PORT}/{DB_NAME}"
)

# Quick connection test
query_test = "SELECT CURRENT_DATABASE();"

try:
    with engine.connect() as conn:
        result = conn.execute(text(query_test))
        for row in result:
            print("Connected to database:", row[0])
except SQLAlchemyError as e:
    print("Database connection failed.")
    print(e)

Connected to database: layereddb

## Load SQL script to count amenities

This SQL script builds the base neighborhood amenity table.

It includes:
- amenity counts per neighborhood
- selected numeric aggregations such as bike lane length, park area, playground area, and average long-term rent
- selected sub-counts used later for accessibility scoring

This is the base table from which we derive:
- accessibility ratio
- spatial density features
- population density features

In [3]:
sql_counts_path = Path("../sql/create_neighborhood_amenity_counts.sql")

with open(sql_counts_path, "r", encoding="utf-8") as f:
    counts_query = f.read()

print(f"Loaded SQL from: {sql_counts_path}")

Loaded SQL from: ../sql/create_neighborhood_amenity_counts.sql

## Build amenity table from SQL counts

In [4]:
try:
    df_features = pd.read_sql(text(counts_query), engine)
    print("Feature table shape:", df_features.shape)
    display(df_features.head())
except SQLAlchemyError as e:
    print("Query execution failed.")
    print(e)

Feature table shape: (96, 82)

,neighborhood_id,neighborhood,district,atm_count,atm_accessible_count,bakery_count,bank_count,bank_accessible_count,bike_lane_length_m,bouldering_spot_count,bouldering_accessible_count,bus_stop_count,bus_stop_accessible_count,dental_office_count,dental_office_accessible_count,diplomatic_mission_count,doctor_count,emergency_station_count,police_station_count,fire_station_count,exhibition_center_count,food_market_count,food_market_accessible_count,gallery_count,gallery_accessible_count,gas_station_count,gas_station_electric_count,government_office_count,hospital_count,hospital_accessible_count,hotel_count,hotel_accessible_count,kindergarten_count,kindergarten_capacity,library_count,library_accessible_count,long_term_listing_count,long_term_avg_price_euro,mall_count,mall_accessible_count,milieuschutz_area_ha,museum_count,museum_accessible_count,night_club_count,night_club_accessible_count,parking_space_count,parking_capacity,parking_disabled_capacity,park_area_sq_m,petstore_count,pharmacy_count,pharmacy_accessible_count,playground_area_sq_m,pool_count,public_artwork_count,recycling_point_count,religious_institution_count,religious_institution_accessible_count,research_institute_count,research_institute_accessible_count,school_count,short_term_listing_count,social_club_count,spaeti_count,supermarket_count,theater_count,theater_accessible_count,cinema_count,stage_theater_count,tram_stop_count,tram_stop_accessible_count,transport_station_entrance_count,transport_station_entrance_accessible_count,transport_station_count,transport_station_accessible_count,university_count,university_accessible_count,venue_count,venue_accessible_count,veterinary_clinic_count,vocational_school_count,vocational_school_accessible_count
0,0401,Charlottenburg,Charlottenburg-Wilmersdorf,54,18,70,21,13,147145.855278,0,0,143,113,59,4,12,88,7,3,3,0,12,6,41,2,82,75,21,10,3,102,45,77,647,12,5,81,1501.555556,4,1,0.0,21,7,12,1,7627,33907.0,27.0,789441.514957,5,39,24,61142.768476,3,93,45,30,10,8,1,24,0,64,88,63,25,8,9,0,18,12,80,16,17,12,9,3,782,162,9,6,0
1,0406,Charlottenburg-Nord,Charlottenburg-Wilmersdorf,4,0,2,0,0,40413.196484,0,0,55,6,1,0,0,2,4,0,4,0,0,0,0,0,4,2,3,0,0,0,0,9,0,1,1,8,449.875000,0,0,0.0,1,0,1,0,1600,6642.0,7.0,82656.392816,0,3,2,18471.688716,1,5,13,3,1,0,0,6,0,8,1,4,0,0,0,0,3,1,9,2,3,1,0,0,9,2,0,0,0
2,0404,Grunewald,Charlottenburg-Wilmersdorf,0,0,1,2,1,66980.626977,1,0,43,1,2,0,25,5,0,0,0,0,0,0,0,0,5,3,3,1,0,7,2,6,0,2,0,10,2821.000000,0,0,0.0,1,0,0,0,3314,8844.0,4.0,166516.611549,0,1,1,6363.970608,6,7,6,3,0,1,0,4,71,8,1,1,1,0,0,0,1,1,0,0,1,1,0,0,18,2,1,1,0
3,0407,Halensee,Charlottenburg-Wilmersdorf,10,1,9,2,0,12257.866992,0,0,18,7,12,0,2,31,0,0,0,0,1,0,0,0,6,4,1,2,0,3,0,11,30,0,0,8,1251.250000,0,0,634.4,0,0,1,0,711,3906.0,0.0,20722.408622,1,4,4,7203.339367,0,6,7,4,0,0,0,1,74,4,7,8,1,0,0,0,1,1,1,0,2,2,0,0,44,6,2,0,0
4,0403,Schmargendorf,Charlottenburg-Wilmersdorf,2,0,6,4,2,50061.686708,0,0,32,3,3,0,8,5,0,0,0,0,1,0,0,0,9,9,2,2,1,2,0,10,310,1,1,17,1356.352941,0,0,0.0,0,0,1,0,2105,9779.0,4.0,45441.374835,1,7,2,13535.220541,2,3,14,5,2,0,0,7,39,5,7,9,0,0,0,0,0,0,0,0,0,0,0,0,33,8,2,0,0

## Basic checks

We inspect:
- shape
- data types
- missing values
- summary statistics

In [5]:
print("Rows:", df_features.shape[0])
print("Columns:", df_features.shape[1])

display(pd.DataFrame({
    "column": df_features.columns,
    "dtype": df_features.dtypes.astype(str).values
}))

missing = (
    df_features.isna()
    .sum()
    .reset_index()
    .rename(columns={"index": "column", 0: "missing_count"})
)

missing["missing_pct"] = (missing["missing_count"] / len(df_features) * 100).round(2)
missing = missing.sort_values(["missing_count", "column"], ascending=[False, True])

display(missing)

display(df_features.describe(include="all").T)

Rows: 96
Columns: 82

                                         column    dtype
0                               neighborhood_id      str
1                                  neighborhood      str
2                                      district      str
3                                     atm_count    int64
4                          atm_accessible_count    int64
5                                  bakery_count    int64
6                                    bank_count    int64
7                         bank_accessible_count    int64
8                            bike_lane_length_m  float64
9                         bouldering_spot_count    int64
10                  bouldering_accessible_count    int64
11                               bus_stop_count    int64
12                    bus_stop_accessible_count    int64
13                          dental_office_count    int64
14               dental_office_accessible_count    int64
15                     diplomatic_mission_count    int64
16                                 doctor_count    int64
17                      emergency_station_count    int64
18                         police_station_count    int64
19                           fire_station_count    int64
20                      exhibition_center_count    int64
21                            food_market_count    int64
22                 food_market_accessible_count    int64
23                                gallery_count    int64
24                     gallery_accessible_count    int64
25                            gas_station_count    int64
26                   gas_station_electric_count    int64
27                      government_office_count    int64
28                               hospital_count    int64
29                    hospital_accessible_count    int64
30                                  hotel_count    int64
31                       hotel_accessible_count    int64
32                           kindergarten_count    int64
33                        kindergarten_capacity    int64
34                                library_count    int64
35                     library_accessible_count    int64
36                      long_term_listing_count    int64
37                     long_term_avg_price_euro  float64
38                                   mall_count    int64
39                        mall_accessible_count    int64
40                         milieuschutz_area_ha  float64
41                                 museum_count    int64
42                      museum_accessible_count    int64
43                             night_club_count    int64
44                  night_club_accessible_count    int64
45                          parking_space_count    int64
46                             parking_capacity  float64
47                    parking_disabled_capacity  float64
48                               park_area_sq_m  float64
49                               petstore_count    int64
50                               pharmacy_count    int64
51                    pharmacy_accessible_count    int64
52                         playground_area_sq_m  float64
53                                   pool_count    int64
54                         public_artwork_count    int64
55                        recycling_point_count    int64
56                  religious_institution_count    int64
57       religious_institution_accessible_count    int64
58                     research_institute_count    int64
59          research_institute_accessible_count    int64
60                                 school_count    int64
61                     short_term_listing_count    int64
62                            social_club_count    int64
63                                 spaeti_count    int64
64                            supermarket_count    int64
65                                theater_count    int64
66                     theater_accessible_count    int64
67                                 cinema_count    int64
68                          stage_theater_count    int64
69                              tram_stop_count    int64
70                   tram_stop_accessible_count    int64
71             transport_station_entrance_count    int64
72  transport_station_entrance_accessible_count    int64
73                      transport_station_count    int64
74           transport_station_accessible_count    int64
75                             university_count    int64
76                  university_accessible_count    int64
77                                  venue_count    int64
78                       venue_accessible_count    int64
79                      veterinary_clinic_count    int64
80                      vocational_school_count    int64
81           vocational_school_accessible_count    int64

                                         column  missing_count  missing_pct
37                     long_term_avg_price_euro              5         5.21
4                          atm_accessible_count              0         0.00
3                                     atm_count              0         0.00
5                                  bakery_count              0         0.00
7                         bank_accessible_count              0         0.00
6                                    bank_count              0         0.00
8                            bike_lane_length_m              0         0.00
10                  bouldering_accessible_count              0         0.00
9                         bouldering_spot_count              0         0.00
12                    bus_stop_accessible_count              0         0.00
11                               bus_stop_count              0         0.00
67                                 cinema_count              0         0.00
14               dental_office_accessible_count              0         0.00
13                          dental_office_count              0         0.00
15                     diplomatic_mission_count              0         0.00
2                                      district              0         0.00
16                                 doctor_count              0         0.00
17                      emergency_station_count              0         0.00
20                      exhibition_center_count              0         0.00
19                           fire_station_count              0         0.00
22                 food_market_accessible_count              0         0.00
21                            food_market_count              0         0.00
24                     gallery_accessible_count              0         0.00
23                                gallery_count              0         0.00
25                            gas_station_count              0         0.00
26                   gas_station_electric_count              0         0.00
27                      government_office_count              0         0.00
29                    hospital_accessible_count              0         0.00
28                               hospital_count              0         0.00
31                       hotel_accessible_count              0         0.00
30                                  hotel_count              0         0.00
33                        kindergarten_capacity              0         0.00
32                           kindergarten_count              0         0.00
35                     library_accessible_count              0         0.00
34                                library_count              0         0.00
36                      long_term_listing_count              0         0.00
39                        mall_accessible_count              0         0.00
38                                   mall_count              0         0.00
40                         milieuschutz_area_ha              0         0.00
42                      museum_accessible_count              0         0.00
41                                 museum_count              0         0.00
1                                  neighborhood              0         0.00
0                               neighborhood_id              0         0.00
44                  night_club_accessible_count              0         0.00
43                             night_club_count              0         0.00
48                               park_area_sq_m              0         0.00
46                             parking_capacity              0         0.00
47                    parking_disabled_capacity              0         0.00
45                          parking_space_count              0         0.00
49                               petstore_count              0         0.00
51                    pharmacy_accessible_count              0         0.00
50                               pharmacy_count              0         0.00
52                         playground_area_sq_m              0         0.00
18                         police_station_count              0         0.00
53                                   pool_count              0         0.00
54                         public_artwork_count              0         0.00
55                        recycling_point_count              0         0.00
57       religious_institution_accessible_count              0         0.00
56                  religious_institution_count              0         0.00
59          research_institute_accessible_count              0         0.00
58                     research_institute_count              0         0.00
60                                 school_count              0         0.00
61                     short_term_listing_count              0         0.00
62                            social_club_count              0         0.00
63                                 spaeti_count              0         0.00
68                          stage_theater_count              0         0.00
64                            supermarket_count              0         0.00
66                     theater_accessible_count              0         0.00
65                                theater_count              0         0.00
70                   tram_stop_accessible_count              0         0.00
69                              tram_stop_count              0         0.00
74           transport_station_accessible_count              0         0.00
73                      transport_station_count              0         0.00
72  transport_station_entrance_accessible_count              0         0.00
71             transport_station_entrance_count              0         0.00
76                  university_accessible_count              0         0.00
75                             university_count              0         0.00
78                       venue_accessible_count              0         0.00
77                                  venue_count              0         0.00
79                      veterinary_clinic_count              0         0.00
81           vocational_school_accessible_count              0         0.00
80                      vocational_school_count              0         0.00

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
neighborhood_id,96,96,0401,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
neighborhood,96,96,Charlottenburg,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
district,96,12,Treptow-Köpenick,15,NaN,NaN,NaN,NaN,NaN,NaN,NaN
atm_count,96.0,NaN,NaN,NaN,11.0625,24.772571,0.0,1.0,3.0,7.25,117.0
atm_accessible_count,96.0,NaN,NaN,NaN,3.020833,6.402268,0.0,0.0,1.0,3.0,37.0
bakery_count,96.0,NaN,NaN,NaN,13.645833,19.745741,0.0,2.0,6.0,15.0,87.0
bank_count,96.0,NaN,NaN,NaN,2.489583,3.968282,0.0,0.0,1.0,3.25,23.0
bank_accessible_count,96.0,NaN,NaN,NaN,1.666667,2.827186,0.0,0.0,1.0,2.0,18.0
bike_lane_length_m,96.0,NaN,NaN,NaN,67242.205795,43652.234468,5092.801969,33369.27393,59937.111982,83574.569642,210128.03059
bouldering_spot_count,96.0,NaN,NaN,NaN,0.375,0.909019,0.0,0.0,0.0,0.0,5.0
bouldering_accessible_count,96.0,NaN,NaN,NaN,0.041667,0.247797,0.0,0.0,0.0,0.0,2.0
bus_stop_count,96.0,NaN,NaN,NaN,56.260417,37.844626,5.0,27.75,47.0,75.75,179.0
bus_stop_accessible_count,96.0,NaN,NaN,NaN,26.572917,26.665864,0.0,5.75,20.0,38.0,123.0
dental_office_count,96.0,NaN,NaN,NaN,8.291667,13.028646,0.0,1.0,3.0,8.0,60.0
dental_office_accessible_count,96.0,NaN,NaN,NaN,0.947917,1.61812,0.0,0.0,0.0,1.0,10.0
diplomatic_mission_count,96.0,NaN,NaN,NaN,2.229167,7.116296,0.0,0.0,0.0,1.0,49.0
doctor_count,96.0,NaN,NaN,NaN,16.822917,24.67643,0.0,2.0,8.0,17.0,116.0
emergency_station_count,96.0,NaN,NaN,NaN,1.875,1.736603,0.0,1.0,2.0,2.25,10.0
police_station_count,96.0,NaN,NaN,NaN,0.666667,1.111345,0.0,0.0,0.0,1.0,6.0
fire_station_count,96.0,NaN,NaN,NaN,1.041667,0.939391,0.0,0.0,1.0,1.25,4.0
exhibition_center_count,96.0,NaN,NaN,NaN,0.041667,0.321728,0.0,0.0,0.0,0.0,3.0
food_market_count,96.0,NaN,NaN,NaN,1.729167,2.81903,0.0,0.0,1.0,2.0,12.0
food_market_accessible_count,96.0,NaN,NaN,NaN,0.4375,1.024053,0.0,0.0,0.0,0.0,6.0
gallery_count,96.0,NaN,NaN,NaN,3.239583,9.687479,0.0,0.0,0.0,1.0,68.0
gallery_accessible_count,96.0,NaN,NaN,NaN,0.416667,1.270447,0.0,0.0,0.0,0.0,9.0
gas_station_count,96.0,NaN,NaN,NaN,19.291667,23.317451,0.0,4.0,9.5,24.0,105.0
gas_station_electric_count,96.0,NaN,NaN,NaN,16.28125,21.913564,0.0,3.0,8.5,18.25,103.0
government_office_count,96.0,NaN,NaN,NaN,4.354167,8.795907,0.0,0.0,1.0,5.25,74.0
hospital_count,96.0,NaN,NaN,NaN,2.583333,3.638006,0.0,0.0,1.0,4.0,25.0
hospital_accessible_count,96.0,NaN,NaN,NaN,1.03125,1.349098,0.0,0.0,0.0,2.0,6.0
hotel_count,96.0,NaN,NaN,NaN,9.15625,19.312024,0.0,1.0,3.0,7.25,129.0
hotel_accessible_count,96.0,NaN,NaN,NaN,4.03125,10.764907,0.0,0.0,1.0,2.25,83.0
kindergarten_count,96.0,NaN,NaN,NaN,24.479167,27.573053,0.0,9.0,15.0,29.0,151.0
kindergarten_capacity,96.0,NaN,NaN,NaN,227.072917,316.793283,0.0,0.0,118.5,293.5,1649.0
library_count,96.0,NaN,NaN,NaN,1.552083,2.912296,0.0,0.0,1.0,2.0,21.0
library_accessible_count,96.0,NaN,NaN,NaN,0.770833,1.372506,0.0,0.0,0.0,1.0,10.0
long_term_listing_count,96.0,NaN,NaN,NaN,32.583333,45.893852,0.0,5.75,11.0,45.75,214.0
long_term_avg_price_euro,91.0,NaN,NaN,NaN,1200.64041,724.450941,348.0,785.256154,1024.5,1428.434921,4959.9
mall_count,96.0,NaN,NaN,NaN,1.083333,1.786892,0.0,0.0,0.0,1.0,10.0
mall_accessible_count,96.0,NaN,NaN,NaN,0.760417,1.28755,0.0,0.0,0.0,1.0,6.0
milieuschutz_area_ha,96.0,NaN,NaN,NaN,102.011458,317.533634,0.0,0.0,0.0,0.0,1585.8
museum_count,96.0,NaN,NaN,NaN,2.53125,7.290878,0.0,0.0,1.0,2.0,65.0
museum_accessible_count,96.0,NaN,NaN,NaN,0.989583,3.958987,0.0,0.0,0.0,1.0,36.0
night_club_count,96.0,NaN,NaN,NaN,1.46875,5.117469,0.0,0.0,0.0,1.0,36.0
night_club_accessible_count,96.0,NaN,NaN,NaN,0.322917,1.200831,0.0,0.0,0.0,0.0,8.0
parking_space_count,96.0,NaN,NaN,NaN,3246.760417,2183.333611,95.0,1409.0,2889.0,4454.75,10534.0
parking_capacity,96.0,NaN,NaN,NaN,13778.260417,9611.417823,541.0,6546.5,11715.5,18224.75,43851.0
parking_disabled_capacity,96.0,NaN,NaN,NaN,15.4375,33.173805,0.0,1.75,8.0,18.0,265.0
park_area_sq_m,96.0,NaN,NaN,NaN,389007.557771,420551.073465,0.0,81797.94724,242363.835505,536665.288372,2542763.903165
petstore_count,96.0,NaN,NaN,NaN,0.854167,1.360953,0.0,0.0,0.0,1.0,8.0
pharmacy_count,96.0,NaN,NaN,NaN,7.03125,7.865251,0.0,2.0,4.0,10.0,39.0
pharmacy_accessible_count,96.0,NaN,NaN,NaN,4.802083,5.53766,0.0,1.0,2.5,6.0,24.0
playground_area_sq_m,96.0,NaN,NaN,NaN,32723.557622,32410.448487,908.188053,8270.932603,22052.799399,49793.360507,136261.133117
pool_count,96.0,NaN,NaN,NaN,1.739583,2.042933,0.0,0.0,1.0,3.0,8.0
public_artwork_count,96.0,NaN,NaN,NaN,18.5,32.153251,0.0,1.0,6.5,21.25,164.0
recycling_point_count,96.0,NaN,NaN,NaN,29.604167,32.007065,0.0,7.75,17.5,45.0,216.0
religious_institution_count,96.0,NaN,NaN,NaN,7.84375,8.509225,0.0,3.0,5.0,10.25,45.0
religious_institution_accessible_count,96.0,NaN,NaN,NaN,2.020833,2.5751,0.0,0.0,1.0,3.0,11.0
research_institute_count,96.0,NaN,NaN,NaN,0.59375,1.738591,0.0,0.0,0.0,0.0,9.0
research_institute_accessible_count,96.0,NaN,NaN,NaN,0.052083,0.266351,0.0,0.0,0.0,0.0,2.0
school_count,96.0,NaN,NaN,NaN,10.75,10.249519,0.0,4.0,8.0,14.25,51.0
short_term_listing_count,96.0,NaN,NaN,NaN,16.260417,31.557214,0.0,0.0,0.0,21.0,199.0
social_club_count,96.0,NaN,NaN,NaN,17.270833,23.26347,0.0,4.0,9.0,20.0,121.0
spaeti_count,96.0,NaN,NaN,NaN,16.572917,33.901015,0.0,1.0,3.0,13.25,162.0
supermarket_count,96.0,NaN,NaN,NaN,14.114583,15.494563,0.0,5.0,8.5,17.0,71.0
theater_count,96.0,NaN,NaN,NaN,2.9375,6.085033,0.0,0.0,1.0,3.0,36.0
theater_accessible_count,96.0,NaN,NaN,NaN,1.0,2.031334,0.0,0.0,0.0,1.0,13.0
cinema_count,96.0,NaN,NaN,NaN,0.958333,2.020509,0.0,0.0,0.0,1.0,9.0
stage_theater_count,96.0,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0
tram_stop_count,96.0,NaN,NaN,NaN,10.197917,16.060818,0.0,0.75,3.0,15.25,84.0
tram_stop_accessible_count,96.0,NaN,NaN,NaN,4.125,8.15927,0.0,0.0,1.0,4.0,49.0
transport_station_entrance_count,96.0,NaN,NaN,NaN,8.53125,18.13804,0.0,0.0,0.0,9.5,119.0
transport_station_entrance_accessible_count,96.0,NaN,NaN,NaN,2.395833,4.942787,0.0,0.0,0.0,2.0,32.0
transport_station_count,96.0,NaN,NaN,NaN,2.90625,4.207958,0.0,0.0,1.0,4.0,26.0
transport_station_accessible_count,96.0,NaN,NaN,NaN,2.34375,3.399158,0.0,0.0,1.0,3.0,22.0
university_count,96.0,NaN,NaN,NaN,1.364583,4.544794,0.0,0.0,0.0,1.0,36.0
university_accessible_count,96.0,NaN,NaN,NaN,0.34375,1.412934,0.0,0.0,0.0,0.0,12.0
venue_count,96.0,NaN,NaN,NaN,83.53125,175.430775,1.0,11.0,24.0,58.0,950.0
venue_accessible_count,96.0,NaN,NaN,NaN,19.729167,40.98844,0.0,3.0,7.0,15.5,290.0
veterinary_clinic_count,96.0,NaN,NaN,NaN,1.822917,2.107604,0.0,0.0,1.0,2.0,9.0
vocational_school_count,96.0,NaN,NaN,NaN,1.28125,1.878987,0.0,0.0,1.0,2.0,9.0
vocational_school_accessible_count,96.0,NaN,NaN,NaN,0.21875,0.52722,0.0,0.0,0.0,0.0,2.0

In [6]:
output_counts_path = Path("../data/neighborhood_features_counts.csv")
output_counts_path.parent.mkdir(parents=True, exist_ok=True)

df_features.to_csv(output_counts_path, index=False)
print(f"Saved counts table to: {output_counts_path}")

Saved counts table to: ../data/neighborhood_features_counts.csv

## Create accessibility score

Accessibility is summarized into one neighborhood-level ratio.

It is computed as:

accessible facilities / total facilities

This gives one interpretable signal of how accessibility-friendly a neighborhood is overall.

All individual `_accessible_count` columns are consolidated into a single
`accessibility_ratio` feature.

After calculation, the original accessibility columns and helper fields are removed
to keep the modeling table clean.

In [7]:
df_model = df_features.copy()

# -----------------------------
# Build accessibility ratio
# -----------------------------

# Find all accessibility columns automatically
accessible_cols = [
    col for col in df_model.columns
    if col.endswith("_accessible_count")
]

# Match each accessible column to its total count column
pairs = []

for acc_col in accessible_cols:
    total_col = acc_col.replace("_accessible_count", "_count")
    if total_col in df_model.columns:
        pairs.append((total_col, acc_col))

print(f"Found {len(pairs)} accessibility pairs")

# Sum accessible and total facilities
accessible_sum = pd.Series(0, index=df_model.index, dtype=float)
total_sum = pd.Series(0, index=df_model.index, dtype=float)

for total_col, acc_col in pairs:
    accessible_sum += df_model[acc_col].fillna(0)
    total_sum += df_model[total_col].fillna(0)

# Add parking accessibility
if {
    "parking_disabled_capacity",
    "parking_capacity"
}.issubset(df_model.columns):

    accessible_sum += df_model["parking_disabled_capacity"].fillna(0)
    total_sum += df_model["parking_capacity"].fillna(0)

# Final ratio
df_model["accessibility_ratio"] = (
    accessible_sum / total_sum.replace(0, np.nan)
)

# -----------------------------
# Drop no-longer-needed columns
# -----------------------------

drop_cols = accessible_cols.copy()

if "parking_disabled_capacity" in df_model.columns:
    drop_cols.append("parking_disabled_capacity")

df_model = df_model.drop(columns=drop_cols)

print("Accessibility columns removed")
print("New shape:", df_model.shape)

display(
    df_model[["neighborhood", "accessibility_ratio"]].head()
)

Found 22 accessibility pairs
Accessibility columns removed
New shape: (96, 59)

          neighborhood  accessibility_ratio
0       Charlottenburg             0.013922
1  Charlottenburg-Nord             0.003415
2            Grunewald             0.001456
3             Halensee             0.005234
4        Schmargendorf             0.002330

## Load neighborhood area from geometry

Neighborhood area is needed to derive:
- spatial density features such as counts per km²
- land-use shares such as park share and playground share

The neighborhood geometry is stored as hex-encoded WKB, so it must be decoded before computing area.

In [8]:
query_area = """
SELECT
    LPAD(neighborhood_id::text, 4, '0') AS neighborhood_id,
    ST_Area(
        ST_Transform(
            ST_SetSRID(
                ST_GeomFromWKB(decode(geometry, 'hex')),
                4326
            ),
            25833
        )
    ) AS area_sq_m
FROM berlin_source_data.neighborhoods
WHERE geometry IS NOT NULL;
"""

df_area = pd.read_sql(text(query_area), engine)

display(df_area.head())
print("Area table shape:", df_area.shape)

  neighborhood_id     area_sq_m
0            0503  5.661235e+06
1            0504  1.088277e+07
2            0903  4.821521e+06
3            0904  6.518400e+06
4            0905  3.498748e+06

Area table shape: (96, 2)

In [9]:
# Merge area into the working feature table
df_model = df_model.merge(df_area, on="neighborhood_id", how="left")

print("Missing area values:", df_model["area_sq_m"].isna().sum())

# Convert to km² for density calculations
df_model["area_sq_km"] = df_model["area_sq_m"] / 1_000_000

display(
    df_model[["neighborhood_id", "neighborhood", "area_sq_m", "area_sq_km"]].head()
)

Missing area values: 0

  neighborhood_id         neighborhood     area_sq_m  area_sq_km
0            0401       Charlottenburg  1.059155e+07   10.591550
1            0406  Charlottenburg-Nord  6.196480e+06    6.196480
2            0404            Grunewald  2.234392e+07   22.343924
3            0407             Halensee  1.266255e+06    1.266255
4            0403        Schmargendorf  3.586366e+06    3.586366

## Calculate spatial density from counts

Some features are better interpreted relative to neighborhood area rather than population.

We use:
- counts per km² for point-based infrastructure and activities
- meters per km² for bike lanes

Area-based features are better expressed as a share of neighborhood area.

This applies to:
- park area
- playground area
- milieuschutz area

In [10]:
area_km_safe = df_model["area_sq_km"].replace(0, np.nan)
area_safe = df_model["area_sq_m"].replace(0, np.nan)

# -----------------------------
# Spatial density: counts per km²
# -----------------------------
spatial_density_features = [
    "bouldering_spot_count",
    "bus_stop_count",
    "cinema_count",
    "dental_office_count",
    "diplomatic_mission_count",
    "doctor_count",
    "emergency_station_count",
    "exhibition_center_count",
    "fire_station_count",
    "food_market_count",
    "gallery_count",
    "gas_station_count",
    "gas_station_electric_count",
    "hospital_count",
    "hotel_count",
    "kindergarten_count",
    "library_count",
    "long_term_listing_count",
    "mall_count",
    "museum_count",
    "night_club_count",
    "parking_capacity",
    "parking_space_count",
    "pharmacy_count",
    "police_station_count",
    "pool_count",
    "public_artwork_count",
    "religious_institution_count",
    "research_institute_count",
    "school_count",
    "short_term_listing_count",
    "social_club_count",
    "spaeti_count",
    "stage_theater_count",
    "supermarket_count",
    "theater_count",
    "tram_stop_count",
    "transport_station_count",
    "transport_station_entrance_count",
    "university_count",
    "venue_count",
    "vocational_school_count",
]

for col in spatial_density_features:
    if col in df_model.columns:
        df_model[f"{col}_per_sq_km"] = df_model[col] / area_km_safe

# -----------------------------
# Linear infrastructure per km²
# -----------------------------
if "bike_lane_length_m" in df_model.columns:
    df_model["bike_lane_length_m_per_sq_km"] = df_model["bike_lane_length_m"] / area_km_safe

# -----------------------------
# Area-share features
# -----------------------------
if "park_area_sq_m" in df_model.columns:
    df_model["park_share"] = df_model["park_area_sq_m"] / area_safe

if "playground_area_sq_m" in df_model.columns:
    df_model["playground_share"] = df_model["playground_area_sq_m"] / area_safe

if "milieuschutz_area_ha" in df_model.columns:
    df_model["milieuschutz_area_sq_m"] = df_model["milieuschutz_area_ha"] * 10_000
    df_model["milieuschutz_share"] = df_model["milieuschutz_area_sq_m"] / area_safe

In [11]:
display(
    df_model[[
        "neighborhood",
        "area_sq_km",
        "bike_lane_length_m_per_sq_km",
        "park_share",
        "playground_share"
    ]]
    .sort_values("bike_lane_length_m_per_sq_km", ascending=False)
    .head(10)
)

,neighborhood,area_sq_km,bike_lane_length_m_per_sq_km,park_share,playground_share
75,Friedenau,1.654282,20108.370165,0.021242,0.007025
6,Wilmersdorf,7.157517,18126.833482,0.029784,0.011321
25,Hansaviertel,0.528038,15545.929000,0.028952,0.004254
58,Wittenau,5.893308,14821.009063,0.067348,0.001973
72,Steglitz,6.782407,14508.992429,0.030859,0.007312
20,Hellersdorf,8.142248,14432.593111,0.135698,0.012833
43,Prenzlauer Berg,11.003473,14126.397098,0.086650,0.010719
4,Schmargendorf,3.586366,13958.890970,0.012671,0.003774
0,Charlottenburg,10.591550,13892.759605,0.074535,0.005773
26,Mitte,10.673582,13006.438505,0.061526,0.007617

## Import population data and calculate population density features

For resident-facing services, counts are more meaningful relative to population.

We therefore calculate counts per 1000 residents for selected features.

In [12]:
pop_path = Path("../data/population_data.csv")
df_pop = pd.read_csv(pop_path, dtype={"neighborhood_id": str})

# Normalize neighborhood_id
df_pop["neighborhood_id"] = df_pop["neighborhood_id"].str.zfill(4)

# Keep only total population
df_pop = df_pop.rename(columns={"Insgesamt": "population"})
df_pop = df_pop[["neighborhood_id", "population"]].copy()

display(df_pop.head())

  neighborhood_id  population
0            0101      108953
1            0102       84913
2            0103        6120
3            0104       16217
4            0105       86662

In [13]:
df_model = df_model.merge(df_pop, on="neighborhood_id", how="left")

print("Missing population values:", df_model["population"].isna().sum())

pop_safe = df_model["population"].replace(0, np.nan)

population_density_features = [
    "kindergarten_count",
    "school_count",
    "vocational_school_count",
    "kindergarten_capacity",
    "long_term_listing_count",
]

for col in population_density_features:
    if col in df_model.columns:
        df_model[f"{col}_per_1000"] = df_model[col] / pop_safe * 1000

Missing population values: 0

## Load SQL script for proximity features

This SQL script computes centroid-based proximity features.

For each neighborhood, it calculates distance to nearby amenities.
Different values of k are used depending on amenity frequency:

- 5 nearest for very common amenities
- 3 nearest for medium-frequency amenities
- 1 nearest for rare / critical amenities

In [14]:
sql_distance_path = Path("../sql/create_neighborhood_proximity_features.sql")

with open(sql_distance_path, "r", encoding="utf-8") as f:
    distance_query = f.read()

print(f"Loaded SQL from: {sql_distance_path}")

Loaded SQL from: ../sql/create_neighborhood_proximity_features.sql

In [15]:
try:
    df_distance = pd.read_sql(text(distance_query), engine)
    print("Distance table shape:", df_distance.shape)
    display(df_distance.head())
except SQLAlchemyError as e:
    print("Distance query execution failed.")
    print(e)

Distance table shape: (96, 34)

,neighborhood_id,neighborhood,district,avg_dist_5_atm_m,avg_dist_5_bakery_m,avg_dist_5_bus_stop_m,avg_dist_3_dental_office_m,avg_dist_3_doctor_m,dist_1_hospital_m,avg_dist_3_kindergarten_m,avg_dist_3_park_m,avg_dist_5_pharmacy_m,avg_dist_3_playground_m,avg_dist_3_school_m,avg_dist_5_spaeti_m,avg_dist_5_supermarket_m,avg_dist_5_tram_stop_m,avg_dist_5_transport_station_m,avg_dist_3_bank_m,dist_1_emergency_station_m,dist_1_fire_station_m,avg_dist_3_food_market_m,avg_dist_3_gas_station_m,avg_dist_3_gas_station_electric_m,avg_dist_3_government_office_m,avg_dist_3_library_m,avg_dist_3_mall_m,avg_dist_3_petstore_m,dist_1_police_station_m,avg_dist_3_pool_m,avg_dist_3_recycling_point_m,avg_dist_3_transport_station_entrance_m,avg_dist_3_veterinary_clinic_m,avg_dist_3_vocational_school_m
0,0101,Mitte,Mitte,326.038650,356.257021,425.035761,772.790702,472.433775,524.281265,392.539379,75.998957,600.227801,244.327377,515.916098,297.292779,373.075277,293.803482,547.573391,559.463390,819.911240,828.388675,335.701826,381.193452,381.193452,520.474876,275.745301,996.883549,1865.975961,819.911240,763.722499,312.912632,422.334341,1002.916412,822.061016
1,0102,Moabit,Mitte,311.582538,360.599120,255.837492,240.894515,404.832017,481.050192,137.007510,399.605036,393.803474,328.012033,549.052821,218.934356,247.095059,384.167323,744.922704,486.500075,852.964674,1008.801233,339.497283,235.942139,235.942139,209.488920,899.875920,927.429918,2516.887471,852.964674,1324.623517,450.935891,347.844116,475.731932,707.314346
2,0103,Hansaviertel,Mitte,659.508177,547.444931,180.581522,783.459897,262.196795,742.482102,306.874703,32.998188,640.210126,171.504319,353.134447,464.114161,503.059441,658.357306,686.909446,855.547337,736.013558,736.013558,574.292738,155.765166,221.778465,588.145734,736.390035,1347.176140,2171.435808,1256.338330,1603.230536,116.692844,591.572178,647.720211,824.276005
3,0104,Tiergarten,Mitte,836.210663,933.855900,354.325274,1230.178684,1081.944780,810.322465,711.451802,307.297730,1186.529734,601.451386,630.848959,941.414009,1060.857267,1285.454555,1275.177209,1287.664733,846.709515,1360.120819,1104.725844,535.283860,535.283860,518.456984,780.420533,1411.977642,1803.987940,1389.744218,1481.619035,862.701946,1107.791604,1230.649688,1303.941450
4,0105,Wedding,Mitte,433.533930,399.588735,315.864620,499.645826,458.259550,822.231913,133.524096,418.381664,629.326911,120.879971,665.181242,313.722655,461.582683,605.191448,998.995395,752.326393,753.817839,753.817839,874.481971,309.676630,309.676630,800.208995,1101.069208,1528.828100,1506.288176,1310.785800,1514.665417,269.387257,588.989041,805.480545,975.045973

## Merge counts and proximity features

In [16]:
df_model = df_model.merge(
    df_distance,
    on=["neighborhood_id", "neighborhood", "district"],
    how="left"
)

print("Final merged table shape:", df_model.shape)
display(df_model.head())

Final merged table shape: (96, 145)

,neighborhood_id,neighborhood,district,atm_count,bakery_count,bank_count,bike_lane_length_m,bouldering_spot_count,bus_stop_count,dental_office_count,diplomatic_mission_count,doctor_count,emergency_station_count,police_station_count,fire_station_count,exhibition_center_count,food_market_count,gallery_count,gas_station_count,gas_station_electric_count,government_office_count,hospital_count,hotel_count,kindergarten_count,kindergarten_capacity,library_count,long_term_listing_count,long_term_avg_price_euro,mall_count,milieuschutz_area_ha,museum_count,night_club_count,parking_space_count,parking_capacity,park_area_sq_m,petstore_count,pharmacy_count,playground_area_sq_m,pool_count,public_artwork_count,recycling_point_count,religious_institution_count,research_institute_count,school_count,short_term_listing_count,social_club_count,spaeti_count,supermarket_count,theater_count,cinema_count,stage_theater_count,tram_stop_count,transport_station_entrance_count,transport_station_count,university_count,venue_count,veterinary_clinic_count,vocational_school_count,accessibility_ratio,area_sq_m,area_sq_km,bouldering_spot_count_per_sq_km,bus_stop_count_per_sq_km,cinema_count_per_sq_km,dental_office_count_per_sq_km,diplomatic_mission_count_per_sq_km,doctor_count_per_sq_km,emergency_station_count_per_sq_km,exhibition_center_count_per_sq_km,fire_station_count_per_sq_km,food_market_count_per_sq_km,gallery_count_per_sq_km,gas_station_count_per_sq_km,gas_station_electric_count_per_sq_km,hospital_count_per_sq_km,hotel_count_per_sq_km,kindergarten_count_per_sq_km,library_count_per_sq_km,long_term_listing_count_per_sq_km,mall_count_per_sq_km,museum_count_per_sq_km,night_club_count_per_sq_km,parking_capacity_per_sq_km,parking_space_count_per_sq_km,pharmacy_count_per_sq_km,police_station_count_per_sq_km,pool_count_per_sq_km,public_artwork_count_per_sq_km,religious_institution_count_per_sq_km,research_institute_count_per_sq_km,school_count_per_sq_km,short_term_listing_count_per_sq_km,social_club_count_per_sq_km,spaeti_count_per_sq_km,stage_theater_count_per_sq_km,supermarket_count_per_sq_km,theater_count_per_sq_km,tram_stop_count_per_sq_km,transport_station_count_per_sq_km,transport_station_entrance_count_per_sq_km,university_count_per_sq_km,venue_count_per_sq_km,vocational_school_count_per_sq_km,bike_lane_length_m_per_sq_km,park_share,playground_share,milieuschutz_area_sq_m,milieuschutz_share,population,kindergarten_count_per_1000,school_count_per_1000,vocational_school_count_per_1000,kindergarten_capacity_per_1000,long_term_listing_count_per_1000,avg_dist_5_atm_m,avg_dist_5_bakery_m,avg_dist_5_bus_stop_m,avg_dist_3_dental_office_m,avg_dist_3_doctor_m,dist_1_hospital_m,avg_dist_3_kindergarten_m,avg_dist_3_park_m,avg_dist_5_pharmacy_m,avg_dist_3_playground_m,avg_dist_3_school_m,avg_dist_5_spaeti_m,avg_dist_5_supermarket_m,avg_dist_5_tram_stop_m,avg_dist_5_transport_station_m,avg_dist_3_bank_m,dist_1_emergency_station_m,dist_1_fire_station_m,avg_dist_3_food_market_m,avg_dist_3_gas_station_m,avg_dist_3_gas_station_electric_m,avg_dist_3_government_office_m,avg_dist_3_library_m,avg_dist_3_mall_m,avg_dist_3_petstore_m,dist_1_police_station_m,avg_dist_3_pool_m,avg_dist_3_recycling_point_m,avg_dist_3_transport_station_entrance_m,avg_dist_3_veterinary_clinic_m,avg_dist_3_vocational_school_m
0,0401,Charlottenburg,Charlottenburg-Wilmersdorf,54,70,21,147145.855278,0,143,59,12,88,7,3,3,0,12,41,82,75,21,10,102,77,647,12,81,1501.555556,4,0.0,21,12,7627,33907.0,789441.514957,5,39,61142.768476,3,93,45,30,8,24,0,64,88,63,25,9,0,18,80,17,9,782,9,6,0.013922,1.059155e+07,10.591550,0.000000,13.501329,0.849734,5.570478,1.132979,8.308510,0.660904,0.0,0.283245,1.132979,3.87101,7.742021,7.081117,0.944149,9.630319,7.269946,1.132979,7.647606,0.37766,1.982713,1.132979,3201.325644,720.102359,3.682181,0.283245,0.283245,8.780585,2.832447,0.755319,2.265957,0.000000,6.042553,8.308510,0.0,5.948138,2.360372,1.699468,1.605053,7.553191,0.849734,73.832443,0.566489,13892.759605,0.074535,0.005773,0.0,0.00000,130566,0.589740,0.183815,0.045954,4.955348,0.620376,322.042804,289.884830,316.220438,286.444421,244.791813,380.812608,246.175464,306.766583,287.287716,46.249897,313.711000,279.028663,238.448888,539.394383,539.383918,358.067683,569.602022,950.097866,660.263775,323.040862,323.040862,321.531893,759.251530,1212.901459,885.261494,836.763893,925.856678,359.337887,195.817547,578.042101,513.063422
1,0406,Charlottenburg-Nord,Charlottenburg-Wilmersdorf,4,2,0,40413.196484,0,55,1,0,2,4,0,4,0,0,0,4,2,3,0,0,9,0,1,8,449.875000,0,0.0,1,1,1600,6642.0,82656.392816,0,3,18471.688716,1,5,13,3,0,6,0,8,1,4,0,0,0,3,9,3,0,9,0,0,0.003415,6.196480e+06,6.196480,0.000000,8.876007,0.000000,0.161382,0.000000,0.322764,0.645528,0.0,0.645528,0.000000,0.00000,0.645528,0.322764,0.000000,0.000000,1.452438,0.161382,1.291056,0.00000,0.161382,0.161382,1071.898933,258.211125,0.484146,0.000000,0.161382,0.806910,0.484146,0.000000,0.968292,0.000000,1.291056,0.161382,0.0,0.645528,0.000000,0.484146,0.484146,1.452438,0.000000,1.452438,0.000000,6521.960580,0.013339,0.002981,0.0,0.00000,19651,0.457992,0.305328,0.000000,0.000000,0.407104,1041.505855,1336.086514,285.683805,1259.967511,1482.522718,2094.890766,223.312437,533.456367,1121.252294,85.372120,555.335208,1383.419073,861.552749,1186.198029,1188.841772,2391.384108,1280.033625,1280.033625,1989.927163,899.573956,951.941418,1095.803806,1621.837802,2734.430782,2331.570125,3248.132053,1879.771439,368.991067,517.639212,1850.454529,2868.487038
2,0404,Grunewald,Charlottenburg-Wilmersdorf,0,1,2,66980.626977,1,43,2,25,5,0,0,0,0,0,0,5,3,3,1,7,6,0,2,10,2821.000000,0,0.0,1,0,3314,8844.0,166516.611549,0,1,6363.970608,6,7,6,3,1,4,71,8,1,1,1,0,0,1,0,1,0,18,1,1,0.001456,2.234392e+07,22.343924,0.044755,1.924461,0.000000,0.089510,1.118872,0.223774,0.000000,0.0,0.000000,0.000000,0.00000,0.223774,0.134265,0.044755,0.313284,0.268529,0.089510,0.447549,0.00000,0.044755,0.000000,395.812307,148.317728,0.044755,0.000000,0.268529,0.313284,0.134265,0.044755,0.179020,3.177598,0.358039,0.044755,0.0,0.044755,0.044755,0.044755,0.044755,0.000000,0.000000,0.805588,0.044755,2997.711046,0.007452,0.000285,0.0,0.00000,11144,0.538406,0.358938,0.089734,0.000000,0.897344,3182.048374,3149.005580,1948.616377,3143.923781,2371.725272,2499.641977,2347.351026,1015.606708,2975.943985,1660.418883,2293.371277,3322.601348,2980.812124,2968.664875,2654.535525,3257.966428,2479.575676,3180.181699,3492.465335,2009.620550,2009.620550,2990.555043,2779.982587,5481.405086,4767.319547,2479.575676,741.545000,1874.079210,3702.600895,2943.315665,2486.594034
3,0407,Halensee,Charlottenburg-Wilmersdorf,10,9,2,12257.866992,0,18,12,2,31,0,0,0,0,1,0,6,4,1,2,3,11,30,0,8,1251.250000,0,634.4,0,1,711,3906.0,20722.408622,1,4,7203.339367,0,6,7,4,0,1,74,4,7,8,1,0,0,1,1,2,0,44,2,0,0.005234,1.266255e+06,1.266255,0.000000,14.215148,0.000000,9.476765,1.579461,24.481644,0.000000,0.0,0.000000,0.789730,0.00000,4.738383,3.158922,1.579461,2.369191,8.687035,0.000000,6.317844,0.00000,0.000000,0.789730,3084.687114,561.498346,3.158922,0.000000,0.000000,4.738383,3.158922,0.000000,0.789730,58.440053,3.158922,5.528113,0.0,6.317844,0.789730,0.789730,1.579461,0.789730,0.000000,34.748140,0.000000,9680.410741,0.016365,0.005689,6344000.0,5.01005,15836,0.694620,0.063147,0.000000,1.894418,0.505178,128.006146,197.110744,208.198952,141.286433,118.742749,185.610869,249.542252,464.858556,362.158406,299.071900,614.864706,263.206503,378.004135,818.505617,825.697853,542.385320,1348.911288,1348.911288,903.618132,340.271091,340.271091,612.879816,1456.626584,2008.862295,1331.437088,1488.782326,1306.896371,373.224138,710.776199,668.478128,1539.265680
4,0403,Schmargendorf,Charlottenburg-Wilmersdorf,2,6,4,50061.686708,0,32,3,8,5,0,0,0,0,1,0,9,9,2,2,2,10,310,1,17,1356.352941,0,0.0,0,1,2105,9779.0,45441.374835,1,7,13535.220541,2,3,14,5,0,7,39,5,7,9,0,0,0,0,0,0,0,33,2,0,0.002330,3.586366e+06,3.586366,0.000000,8.922682,0.000000,0.836501,2.230671,1.394169,0.000000,0.0,0.000000,0.278834,0.00000,2.509504,2.509504,0.557668,0.557668,2.788338,0.278834,4.740175,0.00000,0.000000,0.278834,2726.715853,586.945176,1.951837,0.000000,0.557668,0.836501,1.394169,0.000000,1.951837,10.874519,1.394169,1.951837,0.0,2.509504,0.000000,0.000000,0.000000,0.000000,0.000000,9.201516,0.000000,13958.890970,0.012671,0.003774,0.0,0.00000,23955,0.417449,0.292215,0.000000,12.940931,0.709664,1007.464042,504.590190,354.376077,963.392213,523.494404,703.982603,477.054945,254.442325,446.571909,219.424748,292.740840,422.521135,587.440347,1676.637868,1529.513418,602.268691,1173.422937,2180.125356,786.925609,311.759189,311.759189,795.095401,1139.284895,2823.350248,1873.327319,1173.422937,1167.481876,354.365053,1230.850529,945.861694,1990.076806

## Final feature selection and model table cleanup

At this stage, the dataset contains both:

- raw source variables (for example raw counts and helper columns)
- engineered modeling features (density, shares, proximity)

Before export, we simplify the table by removing raw variables that are now fully represented by engineered features.

### What gets removed
We drop:
- all raw `*_count` columns
- absolute capacity helper columns already normalized
- area helper columns
- population helper column

### What stays
We keep:
- identifiers
- key raw scalar features
- spatial density features
- population-normalized features
- area-share features
- proximity features

This creates the final ML-ready feature table.

In [17]:
# Inspect all current columns with index
for i, col in enumerate(df_model.columns):
    print(f"{i}: {col}")

0: neighborhood_id
1: neighborhood
2: district
3: atm_count
4: bakery_count
5: bank_count
6: bike_lane_length_m
7: bouldering_spot_count
8: bus_stop_count
9: dental_office_count
10: diplomatic_mission_count
11: doctor_count
12: emergency_station_count
13: police_station_count
14: fire_station_count
15: exhibition_center_count
16: food_market_count
17: gallery_count
18: gas_station_count
19: gas_station_electric_count
20: government_office_count
21: hospital_count
22: hotel_count
23: kindergarten_count
24: kindergarten_capacity
25: library_count
26: long_term_listing_count
27: long_term_avg_price_euro
28: mall_count
29: milieuschutz_area_ha
30: museum_count
31: night_club_count
32: parking_space_count
33: parking_capacity
34: park_area_sq_m
35: petstore_count
36: pharmacy_count
37: playground_area_sq_m
38: pool_count
39: public_artwork_count
40: recycling_point_count
41: religious_institution_count
42: research_institute_count
43: school_count
44: short_term_listing_count
45: social_club_count
46: spaeti_count
47: supermarket_count
48: theater_count
49: cinema_count
50: stage_theater_count
51: tram_stop_count
52: transport_station_entrance_count
53: transport_station_count
54: university_count
55: venue_count
56: veterinary_clinic_count
57: vocational_school_count
58: accessibility_ratio
59: area_sq_m
60: area_sq_km
61: bouldering_spot_count_per_sq_km
62: bus_stop_count_per_sq_km
63: cinema_count_per_sq_km
64: dental_office_count_per_sq_km
65: diplomatic_mission_count_per_sq_km
66: doctor_count_per_sq_km
67: emergency_station_count_per_sq_km
68: exhibition_center_count_per_sq_km
69: fire_station_count_per_sq_km
70: food_market_count_per_sq_km
71: gallery_count_per_sq_km
72: gas_station_count_per_sq_km
73: gas_station_electric_count_per_sq_km
74: hospital_count_per_sq_km
75: hotel_count_per_sq_km
76: kindergarten_count_per_sq_km
77: library_count_per_sq_km
78: long_term_listing_count_per_sq_km
79: mall_count_per_sq_km
80: museum_count_per_sq_km
81: night_club_count_per_sq_km
82: parking_capacity_per_sq_km
83: parking_space_count_per_sq_km
84: pharmacy_count_per_sq_km
85: police_station_count_per_sq_km
86: pool_count_per_sq_km
87: public_artwork_count_per_sq_km
88: religious_institution_count_per_sq_km
89: research_institute_count_per_sq_km
90: school_count_per_sq_km
91: short_term_listing_count_per_sq_km
92: social_club_count_per_sq_km
93: spaeti_count_per_sq_km
94: stage_theater_count_per_sq_km
95: supermarket_count_per_sq_km
96: theater_count_per_sq_km
97: tram_stop_count_per_sq_km
98: transport_station_count_per_sq_km
99: transport_station_entrance_count_per_sq_km
100: university_count_per_sq_km
101: venue_count_per_sq_km
102: vocational_school_count_per_sq_km
103: bike_lane_length_m_per_sq_km
104: park_share
105: playground_share
106: milieuschutz_area_sq_m
107: milieuschutz_share
108: population
109: kindergarten_count_per_1000
110: school_count_per_1000
111: vocational_school_count_per_1000
112: kindergarten_capacity_per_1000
113: long_term_listing_count_per_1000
114: avg_dist_5_atm_m
115: avg_dist_5_bakery_m
116: avg_dist_5_bus_stop_m
117: avg_dist_3_dental_office_m
118: avg_dist_3_doctor_m
119: dist_1_hospital_m
120: avg_dist_3_kindergarten_m
121: avg_dist_3_park_m
122: avg_dist_5_pharmacy_m
123: avg_dist_3_playground_m
124: avg_dist_3_school_m
125: avg_dist_5_spaeti_m
126: avg_dist_5_supermarket_m
127: avg_dist_5_tram_stop_m
128: avg_dist_5_transport_station_m
129: avg_dist_3_bank_m
130: dist_1_emergency_station_m
131: dist_1_fire_station_m
132: avg_dist_3_food_market_m
133: avg_dist_3_gas_station_m
134: avg_dist_3_gas_station_electric_m
135: avg_dist_3_government_office_m
136: avg_dist_3_library_m
137: avg_dist_3_mall_m
138: avg_dist_3_petstore_m
139: dist_1_police_station_m
140: avg_dist_3_pool_m
141: avg_dist_3_recycling_point_m
142: avg_dist_3_transport_station_entrance_m
143: avg_dist_3_veterinary_clinic_m
144: avg_dist_3_vocational_school_m

In [18]:
# -----------------------------------
# Inspect columns to be dropped
# -----------------------------------

# 1. All raw count columns
count_cols_to_drop = [
    col for col in df_model.columns
    if col.endswith("_count")
]

# 2. Additional raw helper / absolute columns
extra_cols_to_drop = [
    "bike_lane_length_m",
    "milieuschutz_area_ha",
    "park_area_sq_m",
    "playground_area_sq_m",
    "kindergarten_capacity",
    "parking_capacity",
    "area_sq_m",
    "area_sq_km",
    "milieuschutz_area_sq_m",
    "population",
]

# 3. Final drop list
cols_to_drop = count_cols_to_drop + [
    col for col in extra_cols_to_drop
    if col in df_model.columns
]

drop_preview = pd.DataFrame({
    "column_to_drop": cols_to_drop
})

print(f"Number of columns to drop: {len(cols_to_drop)}")
display(drop_preview)

Number of columns to drop: 58

                      column_to_drop
0                          atm_count
1                       bakery_count
2                         bank_count
3              bouldering_spot_count
4                     bus_stop_count
5                dental_office_count
6           diplomatic_mission_count
7                       doctor_count
8            emergency_station_count
9               police_station_count
10                fire_station_count
11           exhibition_center_count
12                 food_market_count
13                     gallery_count
14                 gas_station_count
15        gas_station_electric_count
16           government_office_count
17                    hospital_count
18                       hotel_count
19                kindergarten_count
20                     library_count
21           long_term_listing_count
22                        mall_count
23                      museum_count
24                  night_club_count
25               parking_space_count
26                    petstore_count
27                    pharmacy_count
28                        pool_count
29              public_artwork_count
30             recycling_point_count
31       religious_institution_count
32          research_institute_count
33                      school_count
34          short_term_listing_count
35                 social_club_count
36                      spaeti_count
37                 supermarket_count
38                     theater_count
39                      cinema_count
40               stage_theater_count
41                   tram_stop_count
42  transport_station_entrance_count
43           transport_station_count
44                  university_count
45                       venue_count
46           veterinary_clinic_count
47           vocational_school_count
48                bike_lane_length_m
49              milieuschutz_area_ha
50                    park_area_sq_m
51              playground_area_sq_m
52             kindergarten_capacity
53                  parking_capacity
54                         area_sq_m
55                        area_sq_km
56            milieuschutz_area_sq_m
57                        population

In [19]:
# -----------------------------------
# Inspect columns that will stay
# -----------------------------------

remaining_cols = [
    col for col in df_model.columns
    if col not in cols_to_drop
]

keep_preview = pd.DataFrame({
    "column_to_keep": remaining_cols
})

print(f"Number of columns to keep: {len(remaining_cols)}")
display(keep_preview)

Number of columns to keep: 87

                                column_to_keep
0                              neighborhood_id
1                                 neighborhood
2                                     district
3                     long_term_avg_price_euro
4                          accessibility_ratio
5              bouldering_spot_count_per_sq_km
6                     bus_stop_count_per_sq_km
7                       cinema_count_per_sq_km
8                dental_office_count_per_sq_km
9           diplomatic_mission_count_per_sq_km
10                      doctor_count_per_sq_km
11           emergency_station_count_per_sq_km
12           exhibition_center_count_per_sq_km
13                fire_station_count_per_sq_km
14                 food_market_count_per_sq_km
15                     gallery_count_per_sq_km
16                 gas_station_count_per_sq_km
17        gas_station_electric_count_per_sq_km
18                    hospital_count_per_sq_km
19                       hotel_count_per_sq_km
20                kindergarten_count_per_sq_km
21                     library_count_per_sq_km
22           long_term_listing_count_per_sq_km
23                        mall_count_per_sq_km
24                      museum_count_per_sq_km
25                  night_club_count_per_sq_km
26                  parking_capacity_per_sq_km
27               parking_space_count_per_sq_km
28                    pharmacy_count_per_sq_km
29              police_station_count_per_sq_km
30                        pool_count_per_sq_km
31              public_artwork_count_per_sq_km
32       religious_institution_count_per_sq_km
33          research_institute_count_per_sq_km
34                      school_count_per_sq_km
35          short_term_listing_count_per_sq_km
36                 social_club_count_per_sq_km
37                      spaeti_count_per_sq_km
38               stage_theater_count_per_sq_km
39                 supermarket_count_per_sq_km
40                     theater_count_per_sq_km
41                   tram_stop_count_per_sq_km
42           transport_station_count_per_sq_km
43  transport_station_entrance_count_per_sq_km
44                  university_count_per_sq_km
45                       venue_count_per_sq_km
46           vocational_school_count_per_sq_km
47                bike_lane_length_m_per_sq_km
48                                  park_share
49                            playground_share
50                          milieuschutz_share
51                 kindergarten_count_per_1000
52                       school_count_per_1000
53            vocational_school_count_per_1000
54              kindergarten_capacity_per_1000
55            long_term_listing_count_per_1000
56                            avg_dist_5_atm_m
57                         avg_dist_5_bakery_m
58                       avg_dist_5_bus_stop_m
59                  avg_dist_3_dental_office_m
60                         avg_dist_3_doctor_m
61                           dist_1_hospital_m
62                   avg_dist_3_kindergarten_m
63                           avg_dist_3_park_m
64                       avg_dist_5_pharmacy_m
65                     avg_dist_3_playground_m
66                         avg_dist_3_school_m
67                         avg_dist_5_spaeti_m
68                    avg_dist_5_supermarket_m
69                      avg_dist_5_tram_stop_m
70              avg_dist_5_transport_station_m
71                           avg_dist_3_bank_m
72                  dist_1_emergency_station_m
73                       dist_1_fire_station_m
74                    avg_dist_3_food_market_m
75                    avg_dist_3_gas_station_m
76           avg_dist_3_gas_station_electric_m
77              avg_dist_3_government_office_m
78                        avg_dist_3_library_m
79                           avg_dist_3_mall_m
80                       avg_dist_3_petstore_m
81                     dist_1_police_station_m
82                           avg_dist_3_pool_m
83                avg_dist_3_recycling_point_m
84     avg_dist_3_transport_station_entrance_m
85              avg_dist_3_veterinary_clinic_m
86              avg_dist_3_vocational_school_m

In [20]:
# -----------------------------------
# Drop raw columns from modeling table
# -----------------------------------

df_model = df_model.drop(
    columns=cols_to_drop,
    errors="ignore"
)

print("Columns dropped successfully")
print("Final shape:", df_model.shape)

display(pd.DataFrame({
    "remaining_column": df_model.columns
}))

Columns dropped successfully
Final shape: (96, 87)

                              remaining_column
0                              neighborhood_id
1                                 neighborhood
2                                     district
3                     long_term_avg_price_euro
4                          accessibility_ratio
5              bouldering_spot_count_per_sq_km
6                     bus_stop_count_per_sq_km
7                       cinema_count_per_sq_km
8                dental_office_count_per_sq_km
9           diplomatic_mission_count_per_sq_km
10                      doctor_count_per_sq_km
11           emergency_station_count_per_sq_km
12           exhibition_center_count_per_sq_km
13                fire_station_count_per_sq_km
14                 food_market_count_per_sq_km
15                     gallery_count_per_sq_km
16                 gas_station_count_per_sq_km
17        gas_station_electric_count_per_sq_km
18                    hospital_count_per_sq_km
19                       hotel_count_per_sq_km
20                kindergarten_count_per_sq_km
21                     library_count_per_sq_km
22           long_term_listing_count_per_sq_km
23                        mall_count_per_sq_km
24                      museum_count_per_sq_km
25                  night_club_count_per_sq_km
26                  parking_capacity_per_sq_km
27               parking_space_count_per_sq_km
28                    pharmacy_count_per_sq_km
29              police_station_count_per_sq_km
30                        pool_count_per_sq_km
31              public_artwork_count_per_sq_km
32       religious_institution_count_per_sq_km
33          research_institute_count_per_sq_km
34                      school_count_per_sq_km
35          short_term_listing_count_per_sq_km
36                 social_club_count_per_sq_km
37                      spaeti_count_per_sq_km
38               stage_theater_count_per_sq_km
39                 supermarket_count_per_sq_km
40                     theater_count_per_sq_km
41                   tram_stop_count_per_sq_km
42           transport_station_count_per_sq_km
43  transport_station_entrance_count_per_sq_km
44                  university_count_per_sq_km
45                       venue_count_per_sq_km
46           vocational_school_count_per_sq_km
47                bike_lane_length_m_per_sq_km
48                                  park_share
49                            playground_share
50                          milieuschutz_share
51                 kindergarten_count_per_1000
52                       school_count_per_1000
53            vocational_school_count_per_1000
54              kindergarten_capacity_per_1000
55            long_term_listing_count_per_1000
56                            avg_dist_5_atm_m
57                         avg_dist_5_bakery_m
58                       avg_dist_5_bus_stop_m
59                  avg_dist_3_dental_office_m
60                         avg_dist_3_doctor_m
61                           dist_1_hospital_m
62                   avg_dist_3_kindergarten_m
63                           avg_dist_3_park_m
64                       avg_dist_5_pharmacy_m
65                     avg_dist_3_playground_m
66                         avg_dist_3_school_m
67                         avg_dist_5_spaeti_m
68                    avg_dist_5_supermarket_m
69                      avg_dist_5_tram_stop_m
70              avg_dist_5_transport_station_m
71                           avg_dist_3_bank_m
72                  dist_1_emergency_station_m
73                       dist_1_fire_station_m
74                    avg_dist_3_food_market_m
75                    avg_dist_3_gas_station_m
76           avg_dist_3_gas_station_electric_m
77              avg_dist_3_government_office_m
78                        avg_dist_3_library_m
79                           avg_dist_3_mall_m
80                       avg_dist_3_petstore_m
81                     dist_1_police_station_m
82                           avg_dist_3_pool_m
83                avg_dist_3_recycling_point_m
84     avg_dist_3_transport_station_entrance_m
85              avg_dist_3_veterinary_clinic_m
86              avg_dist_3_vocational_school_m

In [21]:
df_model.describe(include="all")

,neighborhood_id,neighborhood,district,long_term_avg_price_euro,accessibility_ratio,bouldering_spot_count_per_sq_km,bus_stop_count_per_sq_km,cinema_count_per_sq_km,dental_office_count_per_sq_km,diplomatic_mission_count_per_sq_km,doctor_count_per_sq_km,emergency_station_count_per_sq_km,exhibition_center_count_per_sq_km,fire_station_count_per_sq_km,food_market_count_per_sq_km,gallery_count_per_sq_km,gas_station_count_per_sq_km,gas_station_electric_count_per_sq_km,hospital_count_per_sq_km,hotel_count_per_sq_km,kindergarten_count_per_sq_km,library_count_per_sq_km,long_term_listing_count_per_sq_km,mall_count_per_sq_km,museum_count_per_sq_km,night_club_count_per_sq_km,parking_capacity_per_sq_km,parking_space_count_per_sq_km,pharmacy_count_per_sq_km,police_station_count_per_sq_km,pool_count_per_sq_km,public_artwork_count_per_sq_km,religious_institution_count_per_sq_km,research_institute_count_per_sq_km,school_count_per_sq_km,short_term_listing_count_per_sq_km,social_club_count_per_sq_km,spaeti_count_per_sq_km,stage_theater_count_per_sq_km,supermarket_count_per_sq_km,theater_count_per_sq_km,tram_stop_count_per_sq_km,transport_station_count_per_sq_km,transport_station_entrance_count_per_sq_km,university_count_per_sq_km,venue_count_per_sq_km,vocational_school_count_per_sq_km,bike_lane_length_m_per_sq_km,park_share,playground_share,milieuschutz_share,kindergarten_count_per_1000,school_count_per_1000,vocational_school_count_per_1000,kindergarten_capacity_per_1000,long_term_listing_count_per_1000,avg_dist_5_atm_m,avg_dist_5_bakery_m,avg_dist_5_bus_stop_m,avg_dist_3_dental_office_m,avg_dist_3_doctor_m,dist_1_hospital_m,avg_dist_3_kindergarten_m,avg_dist_3_park_m,avg_dist_5_pharmacy_m,avg_dist_3_playground_m,avg_dist_3_school_m,avg_dist_5_spaeti_m,avg_dist_5_supermarket_m,avg_dist_5_tram_stop_m,avg_dist_5_transport_station_m,avg_dist_3_bank_m,dist_1_emergency_station_m,dist_1_fire_station_m,avg_dist_3_food_market_m,avg_dist_3_gas_station_m,avg_dist_3_gas_station_electric_m,avg_dist_3_government_office_m,avg_dist_3_library_m,avg_dist_3_mall_m,avg_dist_3_petstore_m,dist_1_police_station_m,avg_dist_3_pool_m,avg_dist_3_recycling_point_m,avg_dist_3_transport_station_entrance_m,avg_dist_3_veterinary_clinic_m,avg_dist_3_vocational_school_m
count,96,96,96,91.000000,96.000000,96.000000,96.000000,96.000000,96.000000,96.000000,96.000000,96.000000,96.000000,96.000000,96.000000,96.000000,96.000000,96.000000,96.000000,96.000000,96.000000,96.000000,96.000000,96.000000,96.000000,96.000000,96.000000,96.000000,96.000000,96.000000,96.000000,96.000000,96.000000,96.000000,96.000000,96.000000,96.000000,96.000000,96.0,96.000000,96.000000,96.000000,96.000000,96.000000,96.000000,96.000000,96.000000,96.000000,96.000000,96.000000,96.000000,96.000000,96.000000,96.000000,96.000000,96.000000,96.000000,96.000000,96.000000,96.000000,96.000000,96.000000,96.000000,96.000000,96.000000,96.000000,96.000000,96.000000,96.000000,96.000000,96.000000,96.000000,96.000000,96.000000,96.000000,96.000000,96.000000,96.000000,96.000000,96.000000,96.000000,96.000000,96.000000,96.000000,96.000000,96.000000,96.000000
unique,96,96,12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,0401,Charlottenburg,Treptow-Köpenick,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,1,1,15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,NaN,NaN,NaN,1200.640410,0.005537,0.049348,7.194340,0.116369,1.259743,0.322503,2.678726,0.234644,0.002844,0.127369,0.243813,0.383613,2.493943,2.100708,0.321517,1.061369,3.351810,0.212672,4.062785,0.158135,0.285347,0.176637,1741.748453,403.121335,0.937456,0.082487,0.187127,2.624056,1.033761,0.066021,1.433844,3.070625,2.233353,2.060374,0.0,1.871620,0.380077,1.254821,0.420488,1.072189,0.173160,10.177594,0.167536,8368.975500,0.049695,0.004292,0.303245,0.621875,0.316840,0.027327,5.988394,0.794908,1621.778067,1093.867973,388.489915,1269.654519,899.772546,1222.287040,519.053143,459.396533,1247.863112,472.983549,748.660859,1733.158045,867.817871,1535.984318,2157.296751,1566.326145,962.708253,1168.044895,2385.295381,791.592052,986.776745,1948.363985,2356.116559,2705.755829,2842.017992,2336.278414,1968.870174,551.981713,2098.382726,1954.211778,2536.566936
std,NaN,NaN,NaN,724.450941,0.004317,0.131899,3.810857,0.230213,2.669853,0.975359,5.497318,0.233672,0.023186,0.156433,0.357618,0.970870,2.623077,2.461672,0.458976,1.967732,3.582946,0.361062,5.515211,0.267060,0.719651,0.522676,962.543408,207.829559,0.949524,0.153659,0.242856,4.670709,1.039634,0.213241,1.218369,8.696732,2.553317,3.487827,0.0,1.803570,0.689258,1.710060,0.726388,2.086431,0.552601,17.550739,0.256810,3881.287034,0.066655,0.003954,1.255118,0.300934,0.348422,0.038034,7.990451,1.219342,1220.943126,866.757622,275.360883,1109.203506,812.400080,995.201937,362.004025,357.489249,959.198072,435.097658,592.398669,1751.700045,669.168805,1357.991811,1452.485472,1283.969595,622.688361,704.960573,1744.809850,656.601740,878.849454,1598.607195,1543.663534,1780.097156,1796.076096,1874.508257,1103.408356,433.481120,1667.972735,1371.164827,1758.619010
min,NaN,NaN,NaN,348.000000,0.000000,0.000000,0.766019,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,161.111951,55.035903,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.175306,0.000000,684.701884,0.000000,0.000134,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,128.006146,158.599110,101.934147,88.579950,69.055948,136.941614,103.114649,32.998188,121.767534,43.578661,158.944140,70.619633,118.462573,133.542497,533.253469,153.463394,120.468043,120.468043,335.701826,43.847531,43.847531,150.947551,275.745301,145.370694,390.868860,188.659836,203.613812,27.893653,94.346265,300.989113,343.922646
25%,NaN,NaN,NaN,785.256154,0.002960,0.000000,4.187944,0.000000,0.148865,0.000000,0.284093,0.092304,0.000000,0.000000,0.000000,0.000000,0.537898,0.328056,0.000000,0.154054,1.124876,0.000000,0.689657,0.000000,0.000000,0.000000,1072.760200,258.858253,0.294944,0.000000,0.000000,0.168528,0.393088,0.000000,0.482532,0.000000,0.579079,0.083906,0.0,0.643662,0.000000,0.031612,0.000000,0.000000,0.000000,1.545861,0.000000,5889.947951,0.014348,0.001414,0.000000,0.448395,0.202106,0.000000,0.000000,0.233408,763.892255,495.143904,219.430746,512.024507,393.680740,462.584744,266.475116,232.349428,610.160233,199.320458,381.510000,543.113725,431.238800,597.786737,1133.377328,772.183103,480.434077,664.785908,1145.489190,324.568884,378.590665,735.610527,1405.592556,1511.069249,1723.530249,965.147981,1255.183967,290.361235,581.268563,1169.159985,1287.754190
50%,NaN,NaN,NaN,1024.500000,0.004500,0.000000,6.741737,0.000000,0.441417,0.000000,0.969761,0.165087,0.000000,0.098552,0.125215,0.000000,1.593545,1.128953,0.162373,0.353694,1.990979,0.081194,1.792125,0.000000,0.104196,0.000000,1745.274135,405.996048,0.538535,0.000000,0.130813,0.663054,0.660123,0.000000,1.124641,0.000000,1.175198,0.477035,0.0,1.221106,0.067806,0.496727,0.164167,0.000000,0.000000,3.582658,0.050131,8513.039032,0.030321,0.002989,0.000000,0.571044,0.256822,0.015141,3.027104,0.503099,1280.447554,858.249591,316.069675,902.216464,581.531283,936.193616,406.574093,356.384831,1024.351731,309.231502,579.110993,1181.258567,662.696020,1212.724321,1692.736599,1257.126052,849.837095,1041.869484,1928.737854,540.896283,667.501104,1529.489200,2108.753371,2333.070112,2478.197320,1896.672803,1702.050866,403.577719,1777.227772,1617.644385,2336.978120
75%,NaN,NaN,NaN,1428.434921,0.006875,0.000000,9.509844,0.153626,1.231892,0.128023,2.429614,0.322900,0.000000,0.163739,0.310137,0.156520,3.293689,3.011893,0.437895,0.917552,4.340253,0.261824,5.907546,0.200153,0.215939,0.111544,2222.266202,547.405959,1.519463,0.140569,0.269994,2.824770,1.215136,0.000000,2.109633,2.415533,3.244162,1.871353,0.0,2.681478,0.394629,1.928147,0.584264,1.476467,0.094766,7.790972,0.204346,10700.697802,0.057255,0.006640,0.000000,0.675227,0.332855,0.044635,9.036933,0.884579,2162.682372,1367.047508,429.205655,1714.588079,1212.241796,1695.729714,676.803929,568.761713,1518.716188,598.374541,846.316816,2157.355556,1044.938570,1945.690320,2787.846480,1930.052703,1305.423347,1538.787279,3132.720289,1062.829604,1342.696576,2681.707089,2833.548966,3330.257688,3295.793742,2998.680661,2380.213465,712.847232,3114.953752,2345.079103,3088.618855
max,NaN,NaN,NaN,4959.900000,0.026589,0.816495,16.952071,1.208984,21.761711,7.532060,42.918930,1.297785,0.221877,0.914295,1.893804,6.370870,10.026958,9.649994,2.705421,12.085915,22.970695,1.967474,34.456042,1.414141,6.089802,3.372813,4671.513910,1034.285753,4.231444,0.864786,1.414141,22.982441,4.835936,1.469472,4.889964,58.440053,11.665980,14.944024,0.0,9.067379,3.372813,7.633954,5.681413,11.149022,4.290336,89.004797,1.208984,20108.370165,0.453959,0.018225,9.497816,2.374169,3.246753,0.198866,43.436365,10.121169,5722.780121,4617.331320,1948.616377,5986.170622,4826.237828,6687.687877,2347.351026,2515.038379,6527.440689,2371.639465,3402.592128,8535.989104,4018.331356,6713.725360,7945.705568,8256.683048,3116.027361,3180.181699,9212.047258,3336.332909,4550.306629,8400.672771,9210.242767,8556.079052,9548.292643,9054.327220,6449.648887,2476.566394,7445.193199,8779.693583,9264.134000

## Correlation analysis by feature family

At this stage, the feature table contains three distinct groups of engineered variables:

- **spatial features**  
  amenities normalized by neighborhood area  
  (counts per km², shares, infrastructure density)

- **population-normalized features**  
  amenities normalized by resident population  
  (counts per 1,000 residents)

- **distance-based features**  
  accessibility measures from neighborhood centroid  
  (distance to nearest 1, 3, or 5 amenities)

A single correlation matrix across all features would be difficult to interpret because these groups represent different urban dimensions and operate on different scales.

For example:

- high amenity density often implies lower distance
- population-normalized metrics capture residential service intensity
- spatial density captures land-use concentration

Combining all of them into one matrix would make the strongest spatial signals dominate and may hide meaningful patterns in population or accessibility features.

For this reason, correlation analysis is performed **separately by feature family**.

### 1. Spatial correlation matrix

This matrix evaluates how amenities and infrastructure co-locate spatially across neighborhoods.

It helps identify urban clusters such as:

- healthcare corridors
- cultural districts
- nightlife hubs
- transport-rich areas

Examples of questions addressed:

- Do pharmacies and supermarkets cluster together?
- Are tram stops associated with cultural venues?
- Do parks and playgrounds co-occur?

In [22]:
spatial_cols = [
    col for col in df_model.columns
    if col.endswith("_per_sq_km")
    or col in [
        "park_share",
        "playground_share",
        "milieuschutz_share",
        "bike_lane_length_m_per_sq_km"
    ]
]

corr_spatial = df_model[spatial_cols].corr()

display(corr_spatial)

,bouldering_spot_count_per_sq_km,bus_stop_count_per_sq_km,cinema_count_per_sq_km,dental_office_count_per_sq_km,diplomatic_mission_count_per_sq_km,doctor_count_per_sq_km,emergency_station_count_per_sq_km,exhibition_center_count_per_sq_km,fire_station_count_per_sq_km,food_market_count_per_sq_km,gallery_count_per_sq_km,gas_station_count_per_sq_km,gas_station_electric_count_per_sq_km,hospital_count_per_sq_km,hotel_count_per_sq_km,kindergarten_count_per_sq_km,library_count_per_sq_km,long_term_listing_count_per_sq_km,mall_count_per_sq_km,museum_count_per_sq_km,night_club_count_per_sq_km,parking_capacity_per_sq_km,parking_space_count_per_sq_km,pharmacy_count_per_sq_km,police_station_count_per_sq_km,pool_count_per_sq_km,public_artwork_count_per_sq_km,religious_institution_count_per_sq_km,research_institute_count_per_sq_km,school_count_per_sq_km,short_term_listing_count_per_sq_km,social_club_count_per_sq_km,spaeti_count_per_sq_km,stage_theater_count_per_sq_km,supermarket_count_per_sq_km,theater_count_per_sq_km,tram_stop_count_per_sq_km,transport_station_count_per_sq_km,transport_station_entrance_count_per_sq_km,university_count_per_sq_km,venue_count_per_sq_km,vocational_school_count_per_sq_km,bike_lane_length_m_per_sq_km,park_share,playground_share,milieuschutz_share
bouldering_spot_count_per_sq_km,1.000000,0.291310,0.087169,0.090185,-0.042928,0.059271,0.188273,-0.037365,0.063634,0.139375,0.250038,0.293468,0.284494,0.098461,0.187921,0.333796,0.112776,0.360551,0.226687,0.146933,0.154448,0.230144,0.053820,0.299367,0.240784,0.106020,0.257624,0.373765,0.033115,0.366469,-0.110636,0.452878,0.475341,NaN,0.305633,0.151243,0.206387,0.096836,0.136790,0.066769,0.226587,0.175930,0.157494,0.008798,0.465935,0.067368
bus_stop_count_per_sq_km,0.291310,1.000000,0.447825,0.520623,0.269112,0.516737,0.381626,-0.032684,0.136762,0.495754,0.428328,0.576563,0.548851,0.350096,0.457610,0.675426,0.402229,0.492204,0.308693,0.376599,0.360650,0.710398,0.665393,0.704381,0.341371,0.164546,0.240911,0.703970,0.110242,0.645768,0.245100,0.578933,0.503242,NaN,0.687610,0.505791,0.111660,0.470022,0.560121,0.207548,0.542859,0.456570,0.683461,0.069950,0.619388,0.286462
cinema_count_per_sq_km,0.087169,0.447825,1.000000,0.663920,0.350300,0.623966,0.466355,-0.057497,0.073684,0.540470,0.718314,0.682140,0.728079,0.319475,0.652601,0.705362,0.422257,0.766676,0.351165,0.622207,0.607317,0.550961,0.399808,0.694264,0.422416,0.206436,0.346981,0.680446,0.250478,0.533636,0.241092,0.761745,0.720417,NaN,0.745780,0.870517,0.395174,0.423081,0.810005,0.227271,0.823378,0.658890,0.471473,0.143281,0.473929,-0.027512
dental_office_count_per_sq_km,0.090185,0.520623,0.663920,1.000000,0.206176,0.967675,0.293293,-0.034387,0.021394,0.428736,0.343217,0.517799,0.530080,0.281437,0.390784,0.837720,0.116350,0.743285,0.269540,0.287348,0.236109,0.631302,0.543567,0.741184,0.118541,0.092973,0.117495,0.682612,0.071537,0.473954,0.674395,0.596730,0.517656,NaN,0.774464,0.634874,0.184381,0.385105,0.674862,0.094386,0.621522,0.596747,0.562060,-0.005436,0.368479,0.147467
diplomatic_mission_count_per_sq_km,-0.042928,0.269112,0.350300,0.206176,1.000000,0.227673,0.074862,0.020116,-0.101875,0.317018,0.576524,0.320564,0.336845,0.206985,0.598803,0.171061,0.549693,0.257194,0.129789,0.628168,0.376894,0.172685,0.081056,0.247151,0.102548,0.007592,0.580629,0.293730,0.203779,0.173359,0.131207,0.219542,0.216102,NaN,0.214022,0.562566,0.186113,0.383525,0.461642,0.345706,0.442057,0.153817,0.289146,-0.005362,0.094095,-0.009781
doctor_count_per_sq_km,0.059271,0.516737,0.623966,0.967675,0.227673,1.000000,0.242923,-0.044690,-0.049576,0.477244,0.325474,0.552622,0.556082,0.313464,0.341621,0.828426,0.169124,0.723872,0.273850,0.255911,0.238301,0.625394,0.511962,0.744388,0.131952,0.119652,0.179368,0.702883,0.049861,0.468423,0.722300,0.577593,0.504259,NaN,0.765640,0.643882,0.204121,0.479043,0.617815,0.142163,0.596493,0.527313,0.546894,0.020798,0.388595,0.135269
emergency_station_count_per_sq_km,0.188273,0.381626,0.466355,0.293293,0.074862,0.242923,1.000000,-0.013568,0.691405,0.362354,0.420648,0.499078,0.514543,0.171749,0.398701,0.436659,0.222444,0.467573,0.083154,0.337188,0.399123,0.359455,0.350001,0.350826,0.686052,0.052113,0.144612,0.355202,0.168127,0.253058,0.012373,0.492522,0.500051,NaN,0.426608,0.432848,0.225647,0.168413,0.394166,0.000179,0.465928,0.433695,0.352966,0.101633,0.276567,0.096238
exhibition_center_count_per_sq_km,-0.037365,-0.032684,-0.057497,-0.034387,0.020116,-0.044690,-0.013568,1.000000,-0.038107,-0.012044,-0.048981,-0.030327,-0.042037,-0.003777,-0.003427,-0.056529,-0.042504,0.050775,-0.028881,-0.013140,-0.041893,0.003774,0.000975,-0.009454,0.038159,-0.009685,-0.002769,-0.026980,-0.038380,-0.009733,0.023049,-0.029090,-0.032055,NaN,-0.058812,-0.039840,-0.029179,0.032004,-0.013144,-0.038845,-0.037037,-0.047231,0.045763,-0.024034,-0.056288,-0.029951
fire_station_count_per_sq_km,0.063634,0.136762,0.073684,0.021394,-0.101875,-0.049576,0.691405,-0.038107,1.000000,0.118125,0.119725,0.053496,0.046226,0.062733,0.123642,0.117441,0.061151,0.085871,-0.121073,0.054840,0.075833,0.136920,0.236620,0.054025,0.060475,0.048519,-0.087255,0.069836,0.078177,0.057326,-0.151044,0.107514,0.187925,NaN,0.084821,0.032212,0.089915,-0.043764,0.095308,-0.035590,0.131964,0.176807,0.164570,-0.157268,0.053667,0.228254
food_market_count_per_sq_km,0.139375,0.495754,0.540470,0.428736,0.317018,0.477244,0.362354,-0.012044,0.118125,1.000000,0.615549,0.726736,0.711546,0.488176,0.647667,0.630924,0.641445,0.555593,0.235183,0.397388,0.509747,0.576445,0.377637,0.680751,0.399203,0.230501,0.535520,0.694158,0.179981,0.607511,0.166390,0.615404,0.669049,NaN,0.653390,0.719878,0.441317,0.755849,0.618218,0.271321,0.728316,0.560925,0.587953,0.070479,0.455016,0.175080
gallery_count_per_sq_km,0.250038,0.428328,0.718314,0.343217,0.576524,0.325474,0.420648,-0.048981,0.119725,0.615549,1.000000,0.702490,0.731783,0.327052,0.897039,0.517340,0.689066,0.607390,0.255723,0.886656,0.768711,0.408552,0.237352,0.581567,0.434063,0.147891,0.530785,0.649307,0.283372,0.494846,-0.042453,0.727804,0.730357,NaN,0.570922,0.875516,0.495327,0.581309,0.774244,0.378406,0.892896,0.486910,0.416570,0.098952,0.405089,0.000319
gas_station_count_per_sq_km,0.293468,0.576563,0.682140,0.517799,0.320564,0.552622,0.499078,-0.030327,0.053496,0.726736,0.702490,1.000000,0.988443,0.419166,0.650613,0.707863,0.596640,0.702745,0.324899,0.562153,0.579170,0.646420,0.461131,0.735722,0.570973,0.191033,0.468339,0.750465,0.339543,0.636964,0.210620,0.805755,0.766200,NaN,0.758039,0.798628,0.551568,0.666540,0.659832,0.341680,0.789869,0.536585,0.621141,0.100484,0.518010,0.023610
gas_station_electric_count_per_sq_km,0.284494,0.548851,0.728079,0.530080,0.336845,0.556082,0.514543,-0.042037,0.046226,0.711546,0.731783,0.988443,1.000000,0.410246,0.663033,0.709432,0.594322,0.727572,0.329454,0.596982,0.615553,0.630318,0.449945,0.721448,0.582500,0.199347,0.476625,0.735270,0.358454,0.621162,0.199878,0.822531,0.781223,NaN,0.745703,0.826170,0.545566,0.634174,0.681997,0.341731,0.809361,0.561482,0.607314,0.115648,0.513758,0.014832
hospital_count_per_sq_km,0.098461,0.350096,0.319475,0.281437,0.206985,0.313464,0.171749,-0.003777,0.062733,0.488176,0.327052,0.419166,0.410246,1.000000,0.443646,0.422525,0.303457,0.322312,0.312733,0.305232,0.357584,0.520460,0.317619,0.537070,0.207195,0.268140,0.324064,0.419405,0.393064,0.461440,0.170611,0.397661,0.444366,NaN,0.505184,0.368940,0.449520,0.226901,0.396988,0.231803,0.449622,0.369599,0.450200,0.093317,0.468467,0.100084
hotel_count_per_sq_km,0.187921,0.457610,0.652601,0.390784,0.598803,0.341621,0.398701,-0.003427,0.123642,0.647667,0.897039,0.650613,0.663033,0.443646,1.000000,0.492113,0.610406,0.549509,0.228187,0.811808,0.720273,0.426598,0.268870,0.587668,0.422281,0.150869,0.510526,0.601625,0.282216,0.450476,0.017329,0.645829,0.659893,NaN,0.582039,0.803557,0.460644,0.511431,0.795631,0.317420,0.874728,0.498059,0.463550,0.008306,0.382737,-0.000626
kindergarten_count_per_sq_km,0.333796,0.675426,0.705362,0.837720,0.171061,0.828426,0.436659,-0.056529,0.117441,0.630924,0.517340,0.707863,0.709432,0.422525,0.492113,1.000000,0.312615,0.813410,0.395584,0.348865,0.349083,0.794158,0.617078,0.873758,0.318749,0.286183,0.245849,0.837783,0.071532,0.779168,0.435413,0.838431,0.776859,NaN,0.905527,0.728322,0.393191,0.526964,0.708699,0.143971,0.751456,0.738900,0.697097,0.077680,0.677025,0.171669
library_count_per_sq_km,0.112776,0.402229,0.422257,0.116350,0.549693,0.169124,0.222444,-0.042504,0.061151,0.641445,0.689066,0.596640,0.594322,0.303457,0.610406,0.312615,1.000000,0.303983,0.287322,0.656185,0.495843,0.361307,0.222798,0.416243,0.268602,0.176163,0.561751,0.441742,0.412819,0.482371,-0.112106,0.429283,0.380218,NaN,0.361314,0.639345,0.423976,0.711809,0.539178,0.694469,0.573178,0.271005,0.430525,0.097879,0.338472,0.123182
long_term_listing_count_per_sq_km,0.360551,0.492204,0.766676,0.743285,0.257194,0.723872,0.467573,0.050775,0.085871,0.555593,0.607390,0.702745,0.727572,0.322312,0.549509,0.813410,0.303983,1.000000,0.352537,0.512369,0.562386,0.616394,0.419438,0.720050,0.396967,0.196925,0.391242,0.735390,0.087515,0.592599,0.370687,0.814709,0.766244,NaN,0.791270,0.772237,0.473407,0.438265,0.712148,0.135888,0.767314,0.631737,0.531441,0.077501,0.544367,0.001013
mall_count_per_sq_km,0.226687,0.308693,0.351165,0.269540,0.129789,0.273850,0.083154,-0.028881,-0.121073,0.235183,0.255723,0.324899,0.329454,0.312733,0.228187,0.395584,0.287322,0.352537,1.000000,0.274470,0.263296,0.558948,0.314067,0.528831,0.190651,0.451387,0.396237,0.228115,0.058219,0.547128,0.065330,0.445002,0.257510,NaN,0.551266,0.349087,0.544168,0.213209,0.324123,0.062511,0.305205,0.511764,0.399362,0.415243,0.627207,-0.036787
museum_count_per_sq_km,0.146933,0.376599,0.622207,0.287348,0.628168,0.255911,0.337188,-0.013140,0.054840,0.397388,0.886656,0.562153,0.596982,0.305232,0.811808,0.348865,0.656185,0.512369,0.274470,1.000000,0.770329,0.285527,0.164194,0.413262,0.369924,0.076269,0.469219,0.452630,0.314583,0.314393,0.012198,0.570496,0.486125,NaN,0.419521,0.756803,0.428949,0.411513,0.743068,0.444749,0.743305,0.379910,0.307468,0.097525,0.254854,-0.029498
night_club_count_per_sq_km,0.154448,0.360650,0.607317,0.236109,0.376894,0.238301,0.399123,-0.041893,0.075833,0.509747,0.768711,0.579170,0.615553,0.357584,0.720273,0.349083,0.495843,0.562386,0.263296,0.770329,1.000000,0.310366,0.162081,0.429692,0.539116,0.100331,0.498711,0.441463,0.149836,0.336043,0.019993,0.651525,0.632792,NaN,0.480784,0.700287,0.454439,0.354444,0.576833,0.223461,0.755324,0.406565,0.249288,0.246936,0.389658,0.037730
parking_capacity_per_sq_km,0.230144,0.710398,0.550961,0.631302,0.172685,0.625394,0.359455,0.003774,0.136920,0.576445,0.408552,0.646420,0.630318,0.520460,0.426598,0.794158,0.361307,0.616394,0.558948,0.285527,0.310366,1.000000,0.858465,0.864686,0.277103,0.351499,0.330090,0.670337,0.094638,0.789333,0.322417,0.656886,0.590592,NaN,0.856874,0.575167,0.479535,0.455558,0.558214,0.194193,0.602113,0.669186,0.865955,0.156462,0.708851,0.138456
parking_space_count_per_sq_km,0.053820,0.665393,0.399808,0.543567,0.081056,0.511962,0.350001,0.000975,0.236620,0.377637,0.237352,0.461131,0.449945,0.317619,0.268870,0.617078,0.222798,0.419438,0.314067,0.164194,0.162081,0.858465,1.000000,0.652226,0.153462,0.189993,0.073977,0.516134,0.099548,0.567144,0.261455,0.417543,0.355969,NaN,0.625163,0.378296,0.198832,0.281802,0.402654,0.179878,0.406436,0.510085,0.796450,0.023149,0.462594,0.157736
pharmacy_count_per_sq_km,0.299367,0.704381,0.694264,0.741184,0.247151,0.744388,0.350826,-0.009454,0.054025,0.680751,0.581567,0.735722,0.721448,0.537070,0.587668,0.873758,0.416243,0.720050,0.528831,0.413262,0.429692,0.864686,0.652226,1.000000,0.344869,0.402822,0.368096,0.839449,0.156498,0.785487,0.378051,0.792154,0.747215,NaN,0.945503,0.736987,0.431396,0.574652,0.712440,0.229431,0.781543,0.688241,0.715711,0.184165,0.696199,0.134073
police_station_count_per_sq_km,0.240784,0.341371,0.422416,0.118541,0.102548,0.131952,0.686052,0.038159,0.060475,0.399203,0.434063,0.570973,0.582500,0.207195,0.422281,0.318749,0.268602,0.396967,0.190651,0.369924,0.539116,0.277103,0.153462,0.344869,1.000000,0.051791,0.282214,0.318883,0.101633,0.260062,-0.054606,0.515009,0.499975,NaN,0.404114,0.431634,0.268878,0.228989,0.290414,0.051585,0.451054,0.323699,0.228991,0.353893,0.342906,-0.054683
pool_count_per_sq_km,0.106020,0.164546,0.206436,0.092973,0.007592,0.119652,0.052113,-0.009685,0.048519,0.230501,0.147891,0.191033,0.199347,0.268140,0.150869,0.286183,0.176163,0.196925,0.451387,0.076269,0.100331,0.351499,0.189993,0.402822,0.051791,1.000000,0.113198,0.222472,-0.026706,0.391070,-0.077825,0.298152,0.283277,NaN,0.363757,0.198960,0.279973,0.070048,0.210796,0.154169,0.261145,0.314088,0.226205,0.055061,0.412731,-0.037164
public_artwork_count_per_sq_km,0.257624,0.240911,0.346981,0.117495,0.580629,0.179368,0.144612,-0.002769,-0.087255,0.535520,0.530785,0.468339,0.476625,0.324064,0.510526,0.245849,0.561751,0.391242,0.396237,0.469219,0.498711,0.330090,0.073977,0.368096,0.282214,0.113198,1.000000,0.309835,0.140994,0.385523,0.035877,0.391457,0.374831,NaN,0.346067,0.588442,0.478079,0.492378,0.391123,0.229760,0.448470,0.284915,0.332231,0.231068,0.389933,-0.049808
religious_institution_count_per_sq_km,0.373765,0.703970,0.680446,0.682612,0.293730,0.702883,0.355202,-0.026980,0.069836,0.694158,0.649307,0.750465,0.735270,0.419405,0.601625,0.837783,0.441742,0.735390,0.228115,0.452630,0.441463,0.670337,0.516134,0.839449,0.318883,0.222472,0.309835,1.000000,0.127978,0.701994,0.338088,0.801384,0.807931,NaN,0.804685,0.756583,0.314000,0.665160,0.712879,0.294436,0.766935,0.568087,0.625941,-0.000725,0.579433,0.198622
research_institute_count_per_sq_km,0.033115,0.110242,0.250478,0.071537,0.203779,0.049861,0.168127,-0.038380,0.078177,0.179981,0.283372,0.339543,0.358454,0.393064,0.282216,0.071532,0.412819,0.087515,0.058219,0.314583,0.149836,0.094638,0.099548,0.156498,0.101633,-0.026706,0.140994,0.127978,1.000000,0.016345,-0.031481,0.151879,0.151247,NaN,0.110933,0.221868,0.166371,0.131234,0.244771,0.497627,0.245502,0.076344,0.166334,-0.048296,0.024395,-0.058881
school_count_per_sq_km,0.366469,0.645768,0.533636,0.473954,0.173359,0.468423,0.253058,-0.009733,0.057326,0.607511,0.494846,0.636964,0.621162,0.461440,0.450476,0.779168,0.482371,0.592599,0.547128,0.314393,0.336043,0.789333,0.567144,0.785487,0.260062,0.391070,0.385523,0.701994,0.016345,1.000000,0.078112,0.756016,0.655371,NaN,0.766508,0.601269,0.527251,0.531436,0.572908,0.213513,0.610048,0.619633,0.691223,0.208269,0.799725,0.245288
short_term_listing_count_per_sq_km,-0.110636,0.245100,0.241092,0.674395,0.131207,0.722300,0.012373,0.023049,-0.151044,0.166390,-0.042453,0.210620,0.199878,0.170611,0.017329,0.435413,-0.112106,0.370687,0.065330,0.012198,0.019993,0.322417,0.261455,0.378051,-0.054606,-0.077825,0.035877,0.338088,-0.031481,0.078112,1.000000,0.205719,0.115722,NaN,0.422354,0.245546,0.012410,0.183238,0.214038,-0.075763,0.199030,0.187238,0.227675,-0.095823,0.085859,0.210854
social_club_count_per_sq_km,0.452878,0.578933,0.761745,0.596730,0.219542,0.577593,0.492522,-0.029090,0.107514,0.615404,0.727804,0.805755,0.822531,0.397661,0.645829,0.838431,0.429283,0.814709,0.445002,0.570496,0.651525,0.656886,0.417543,0.792154,0.515009,0.298152,0.391457,0.801384,0.151879,0.756016,0.205719,1.000000,0.909688,NaN,0.836073,0.791367,0.559288,0.483088,0.709621,0.168343,0.841684,0.695191,0.538352,0.195779,0.730635,0.119418
spaeti_count_per_sq_km,0.475341,0.503242,0.720417,0.517656,0.216102,0.504259,0.500051,-0.032055,0.187925,0.669049,0.730357,0.766200,0.781223,0.444366,0.659893,0.776859,0.380218,0.766244,0.257510,0.486125,0.632792,0.590592,0.355969,0.747215,0.499975,0.283277,0.374831,0.807931,0.151247,0.655371,0.115722,0.909688,1.000000,NaN,0.785598,0.758169,0.491249,0.472784,0.634054,0.182258,0.859267,0.649892,0.495129,0.082556,0.617782,0.114823
stage_theater_count_per_sq_km,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
supermarket_count_per_sq_km,0.305633,0.687610,0.745780,0.774464,0.214022,0.765640,0.426608,-0.058812,0.084821,0.653390,0.570922,0.758039,0.745703,0.505184,0.582039,0.905527,0.361314,0.791270,0.551266,0.419521,0.480784,0.856874,0.625163,0.945503,0.404114,0.363757,0.346067,0.804685,0.110933,0.766508,0.422354,0.836073,0.785598,NaN,1.000000,0.749727,0.499922,0.505291,0.717220,0.134715,0.809338,0.720042,0.692287,0.166268,0.723373,0.133338
theater_count_per_sq_km,0.151243,0.505791,0.870517,0.634874,0.562566,0.643882,0.432848,-0.039840,0.032212,0.719878,0.875516,0.798628,0.826170,0.368940,0.803557,0.728322,0.639345,0.772237,0.349087,0.756803,0.700287,0.575167,0.378296,0.736987,0.431634,0.198960,0.588442,0.756583,0.221868,0.601269,0.245546,0.791367,0.758169,NaN,0.749727,1.000000,0.488039,0.674655,0.859472,0.350402,0.920259,0.628175,0.560301,0.146892,0.469492,0.000631
tram_stop_count_per_sq_km,0.206387,0.111660,0.395174,0.184381,0.186113,0.204121,0.225647,-0.029179,0.089915,0.441317,0.495327,0.551568,0.545566,0.449520,0.460644,0.393191,0.423976,0.473407,0.544168,0.428949,0.454439,0.479535,0.198832,0.431396,0.268878,0.279973,0.478079,0.314000,0.166371,0.527251,0.012410,0.559288,0.491249,NaN,0.499922,0.488039,1.000000,0.355294,0.350921,0.217152,0.495968,0.470109,0.421665,0.141034,0.499389,-0.068065
transport_station_count_per_sq_km,0.096836,0.470022,0.423081,0.385105,0.383525,0.479043,0.168413,0.032004,-0.043764,0.755849,0.581309,0.666540,0.634174,0.226901,0.511431,0.526964,0.711809,0.438265,0.213209,0.411513,0.354444,0.455558,0.281802,0.574652,0.228989,0.070048,0.492378,0.665160,0.131234,0.531436,0.183238,0.483088,0.472784,NaN,0.505291,0.674655,0.355294,1.000000,0.604250,0.438505,0.577013,0.306277,0.525062,0.033699,0.351996,0.066760
transport_station_entrance_count_per_sq_km,0.136790,0.560121,0.810005,0.674862,0.461642,0.617815,0.394166,-0.013144,0.095308,0.618218,0.774244,0.659832,0.681997,0.396988,0.795631,0.708699,0.539178,0.712148,0.324123,0.743068,0.576833,0.558214,0.402654,0.712440,0.290414,0.210796,0.391123,0.712879,0.244771,0.572908,0.214038,0.709621,0.634054,NaN,0.717220,0.859472,0.350921,0.604250,1.000000,0.298934,0.841577,0.616461,0.577050,0.020130,0.447699,-0.010089
university_count_per_sq_km,0.066769,0.207548,0.227271,0.094386,0.345706,0.142163,0.000179,-0.038845,-0.035590,0.271321,0.378406,0.341680,0.341731,0.231803,0.317420,0.143971,0.694469,0.135888,0.062511,0.444749,0.223461,0.194193,0.179878,0.229431,0.051585,0.154169,0.229760,0.294436,0.497627,0.213513,-0.075763,0.168343,0.182258,NaN,0.134715,0.350402,0.217152,0.438505,0.298934,1.000000,0.299183,0.101074,0.266947,-0.051994,0.075856,-0.050258
venue_count_per_sq_km,0.226587,0.542859,0.823378,0.621522,0.442057,0.596493,0.465928,-0.037037,0.131964,0.728316,0.892896,0.789869,0.809361,0.449622,0.874728,0.751456,0.573178,0.767314,0.305205,0.743305,0.755324,0.602113,0.406436,0.781543,0.451054,0.261145,0.448470,0.766935,0.245502,0.610048,0.199030,0.841684,0.859267,NaN,0.809338,0.920259,0.495968,0.577013,0.841577,0.299183,1.000000,0.644849,0.546987,0.077781,0.512013,0.063597
vocational_school_count_per_sq_km,0.175930,0.456570,0.658890,0.596747,0.153817,0.527313,0.433695,-0.047231,0.176807,0.560925,0.486910,0.536585,0.561482,0.369599,0.498059,0.738900,0.271005,0.631737,0.511764,0.379910,0.406565,0.669186,0.510085,0.688241,0.323699,0.314088,0.284915,0.568087,0.076344,0.619633,0.187238,0.695191,0.649892,NaN,0.720042,0.628175,0.470109,0.306277,0.616461,0.101074,0.644849,1.000000,0.556681,0.125639,0.543022,0.149854
bike_lane_length_m_per_sq_km,0.157494,0.683461,0.471473,0.562060,0.289146,0.546894,0.352966,0.045763,0.164570,0.587953,0.416570,0.621141,0.607314,0.450200,0.463550,0.697097,0.430525,0.531441,0.399362,0.307468,0.249288,0.865955,0.796450,0.715711,0.228991,0.226205,0.332231,0.625941,0.166334,0.691223,0.227675,0.538352,0.495129,NaN,0.692287,0.560301,0.421665,0.525062,0.577050,0.266947,0.546987,0.556681,1.000000,0.070034,0.539946,0.096420

### 2. Population-normalized correlation matrix

This matrix focuses on service availability relative to the number of residents.

It is particularly useful for understanding:

- family-oriented neighborhoods
- educational service intensity
- housing pressure indicators

Examples of questions addressed:

- Do neighborhoods with more schools per resident also have more kindergartens?
- Does long-term housing supply scale with family services?

In [23]:
population_cols = [
    col for col in df_model.columns
    if col.endswith("_per_1000")
]

corr_population = df_model[population_cols].corr()

display(corr_population)

,kindergarten_count_per_1000,school_count_per_1000,vocational_school_count_per_1000,kindergarten_capacity_per_1000,long_term_listing_count_per_1000
kindergarten_count_per_1000,1.000000,0.568598,-0.043677,-0.020165,-0.054592
school_count_per_1000,0.568598,1.000000,-0.066872,-0.077241,-0.099807
vocational_school_count_per_1000,-0.043677,-0.066872,1.000000,-0.167645,-0.060089
kindergarten_capacity_per_1000,-0.020165,-0.077241,-0.167645,1.000000,-0.011747
long_term_listing_count_per_1000,-0.054592,-0.099807,-0.060089,-0.011747,1.000000

### 3. Distance-based correlation matrix

This matrix focuses on accessibility patterns.

It helps identify neighborhoods with similar proximity profiles.

Examples of questions addressed:

- Do neighborhoods close to supermarkets also tend to be close to pharmacies?
- Is transport accessibility linked to healthcare accessibility?
- Which services tend to be jointly accessible?

This separation improves interpretability and allows each urban dimension to be analyzed on its own terms.

In [24]:
distance_cols = [
    col for col in df_model.columns
    if "_dist_" in col or col.startswith("dist_")
]

corr_distance = df_model[distance_cols].corr()

display(corr_distance)

,avg_dist_5_atm_m,avg_dist_5_bakery_m,avg_dist_5_bus_stop_m,avg_dist_3_dental_office_m,avg_dist_3_doctor_m,dist_1_hospital_m,avg_dist_3_kindergarten_m,avg_dist_3_park_m,avg_dist_5_pharmacy_m,avg_dist_3_playground_m,avg_dist_3_school_m,avg_dist_5_spaeti_m,avg_dist_5_supermarket_m,avg_dist_5_tram_stop_m,avg_dist_5_transport_station_m,avg_dist_3_bank_m,dist_1_emergency_station_m,dist_1_fire_station_m,avg_dist_3_food_market_m,avg_dist_3_gas_station_m,avg_dist_3_gas_station_electric_m,avg_dist_3_government_office_m,avg_dist_3_library_m,avg_dist_3_mall_m,avg_dist_3_petstore_m,dist_1_police_station_m,avg_dist_3_pool_m,avg_dist_3_recycling_point_m,avg_dist_3_transport_station_entrance_m,avg_dist_3_veterinary_clinic_m,avg_dist_3_vocational_school_m
avg_dist_5_atm_m,1.000000,0.862774,0.454824,0.768263,0.666633,0.594420,0.574422,0.634433,0.825867,0.766603,0.645310,0.834225,0.740314,0.684801,0.862313,0.646765,0.304326,0.192422,0.796090,0.700526,0.732726,0.766738,0.765160,0.730469,0.808409,0.606905,0.298956,0.536953,0.746815,0.706294,0.581015
avg_dist_5_bakery_m,0.862774,1.000000,0.510019,0.887182,0.776717,0.694880,0.683941,0.736683,0.919639,0.874769,0.783727,0.843779,0.869094,0.603644,0.859254,0.796239,0.358539,0.211349,0.792153,0.747816,0.799532,0.838531,0.829817,0.770401,0.808801,0.736655,0.304186,0.629156,0.688806,0.792981,0.646980
avg_dist_5_bus_stop_m,0.454824,0.510019,1.000000,0.485330,0.455233,0.319616,0.738320,0.556018,0.512973,0.578820,0.524870,0.413324,0.625554,0.316882,0.396614,0.439126,0.408295,0.359266,0.424086,0.559791,0.455473,0.426251,0.394387,0.448184,0.436780,0.317630,-0.014471,0.599051,0.421309,0.494536,0.307652
avg_dist_3_dental_office_m,0.768263,0.887182,0.485330,1.000000,0.821522,0.733934,0.674089,0.713973,0.900262,0.787762,0.794443,0.772140,0.847491,0.457576,0.802998,0.864020,0.286271,0.199725,0.792601,0.723788,0.807181,0.783672,0.831421,0.742400,0.724510,0.703816,0.257556,0.529450,0.656634,0.815028,0.663519
avg_dist_3_doctor_m,0.666633,0.776717,0.455233,0.821522,1.000000,0.737669,0.571400,0.652604,0.806949,0.746353,0.706342,0.587193,0.834911,0.361018,0.710768,0.791115,0.297084,0.168791,0.680016,0.651773,0.716162,0.666897,0.683535,0.590337,0.510498,0.654849,0.153307,0.540839,0.597413,0.704728,0.555848
dist_1_hospital_m,0.594420,0.694880,0.319616,0.733934,0.737669,1.000000,0.495746,0.563583,0.779610,0.644920,0.627103,0.566931,0.688563,0.341016,0.640057,0.750828,0.208393,0.145693,0.627913,0.497980,0.639835,0.671081,0.699303,0.576057,0.510423,0.568985,0.193378,0.484220,0.574130,0.681489,0.521624
avg_dist_3_kindergarten_m,0.574422,0.683941,0.738320,0.674089,0.571400,0.495746,1.000000,0.671050,0.668614,0.768295,0.747107,0.537549,0.749981,0.377741,0.556134,0.617022,0.355648,0.290004,0.553409,0.581791,0.549235,0.554704,0.578865,0.531833,0.560630,0.449114,0.188239,0.588631,0.542150,0.583040,0.435338
avg_dist_3_park_m,0.634433,0.736683,0.556018,0.713973,0.652604,0.563583,0.671050,1.000000,0.723534,0.775506,0.742006,0.649727,0.763834,0.443549,0.696923,0.760164,0.315449,0.190232,0.677850,0.677201,0.656527,0.721802,0.756640,0.678219,0.642460,0.687048,0.276964,0.577552,0.515255,0.700321,0.620826
avg_dist_5_pharmacy_m,0.825867,0.919639,0.512973,0.900262,0.806949,0.779610,0.668614,0.723534,1.000000,0.840647,0.780737,0.813551,0.903750,0.517438,0.870161,0.864074,0.275443,0.154254,0.826753,0.664504,0.740815,0.825378,0.842795,0.775442,0.769971,0.738331,0.257621,0.620390,0.715967,0.842567,0.673619
avg_dist_3_playground_m,0.766603,0.874769,0.578820,0.787762,0.746353,0.644920,0.768295,0.775506,0.840647,1.000000,0.804592,0.688609,0.878610,0.449614,0.751035,0.748249,0.374718,0.246948,0.677859,0.699667,0.726974,0.734237,0.769622,0.678272,0.744872,0.644523,0.189896,0.626104,0.580488,0.729848,0.585865
avg_dist_3_school_m,0.645310,0.783727,0.524870,0.794443,0.706342,0.627103,0.747107,0.742006,0.780737,0.804592,1.000000,0.707281,0.789050,0.301912,0.690280,0.836472,0.201352,0.098939,0.700212,0.652532,0.706464,0.747067,0.806953,0.672441,0.685203,0.675907,0.181375,0.574906,0.479765,0.751030,0.649585
avg_dist_5_spaeti_m,0.834225,0.843779,0.413324,0.772140,0.587193,0.566931,0.537549,0.649727,0.813551,0.688609,0.707281,1.000000,0.700483,0.665963,0.881571,0.687318,0.285825,0.140132,0.837412,0.650901,0.696580,0.865147,0.833680,0.846587,0.807094,0.785886,0.349072,0.550768,0.651569,0.796581,0.754413
avg_dist_5_supermarket_m,0.740314,0.869094,0.625554,0.847491,0.834911,0.688563,0.749981,0.763834,0.903750,0.878610,0.789050,0.700483,1.000000,0.439430,0.772987,0.828124,0.367923,0.266278,0.732206,0.742786,0.716057,0.715028,0.746694,0.693363,0.677710,0.664802,0.177336,0.685371,0.661574,0.770765,0.622173
avg_dist_5_tram_stop_m,0.684801,0.603644,0.316882,0.457576,0.361018,0.341016,0.377741,0.443549,0.517438,0.449614,0.301912,0.665963,0.439430,1.000000,0.649798,0.308385,0.305472,0.243490,0.557146,0.521815,0.482879,0.546196,0.413053,0.634791,0.480462,0.442111,0.236447,0.558722,0.521577,0.402720,0.355849
avg_dist_5_transport_station_m,0.862313,0.859254,0.396614,0.802998,0.710768,0.640057,0.556134,0.696923,0.870161,0.751035,0.690280,0.881571,0.772987,0.649798,1.000000,0.743336,0.256016,0.100278,0.876308,0.683114,0.735994,0.865109,0.842641,0.821685,0.751802,0.798730,0.412576,0.546587,0.819978,0.793989,0.731163
avg_dist_3_bank_m,0.646765,0.796239,0.439126,0.864020,0.791115,0.750828,0.617022,0.760164,0.864074,0.748249,0.836472,0.687318,0.828124,0.308385,0.743336,1.000000,0.191220,0.114556,0.766918,0.608635,0.705937,0.778011,0.843660,0.698570,0.659730,0.710488,0.218009,0.496100,0.555082,0.843465,0.714929
dist_1_emergency_station_m,0.304326,0.358539,0.408295,0.286271,0.297084,0.208393,0.355648,0.315449,0.275443,0.374718,0.201352,0.285825,0.367923,0.305472,0.256016,0.191220,1.000000,0.774065,0.254150,0.386961,0.319653,0.201626,0.170530,0.267538,0.316645,0.301022,0.006880,0.275210,0.159291,0.232808,0.176117
dist_1_fire_station_m,0.192422,0.211349,0.359266,0.199725,0.168791,0.145693,0.290004,0.190232,0.154254,0.246948,0.098939,0.140132,0.266278,0.243490,0.100278,0.114556,0.774065,1.000000,0.109409,0.246955,0.173821,0.041769,0.079556,0.167485,0.190605,0.049541,-0.076169,0.193037,0.086446,0.149562,0.022417
avg_dist_3_food_market_m,0.796090,0.792153,0.424086,0.792601,0.680016,0.627913,0.553409,0.677850,0.826753,0.677859,0.700212,0.837412,0.732206,0.557146,0.876308,0.766918,0.254150,0.109409,1.000000,0.655299,0.705798,0.806919,0.839414,0.811192,0.723283,0.789969,0.431831,0.497165,0.715612,0.769096,0.736957
avg_dist_3_gas_station_m,0.700526,0.747816,0.559791,0.723788,0.651773,0.497980,0.581791,0.677201,0.664504,0.699667,0.652532,0.650901,0.742786,0.521815,0.683114,0.608635,0.386961,0.246955,0.655299,1.000000,0.913125,0.636404,0.672043,0.588349,0.575919,0.577797,0.305398,0.580926,0.539600,0.613267,0.510525
avg_dist_3_gas_station_electric_m,0.732726,0.799532,0.455473,0.807181,0.716162,0.639835,0.549235,0.656527,0.740815,0.726974,0.706464,0.696580,0.716057,0.482879,0.735994,0.705937,0.319653,0.173821,0.705798,0.913125,1.000000,0.736812,0.778358,0.663876,0.616563,0.631390,0.338763,0.538408,0.561237,0.697056,0.566132
avg_dist_3_government_office_m,0.766738,0.838531,0.426251,0.783672,0.666897,0.671081,0.554704,0.721802,0.825378,0.734237,0.747067,0.865147,0.715028,0.546196,0.865109,0.778011,0.201626,0.041769,0.806919,0.636404,0.736812,1.000000,0.859180,0.841073,0.725988,0.822670,0.418832,0.586466,0.682312,0.841859,0.806280
avg_dist_3_library_m,0.765160,0.829817,0.394387,0.831421,0.683535,0.699303,0.578865,0.756640,0.842795,0.769622,0.806953,0.833680,0.746694,0.413053,0.842641,0.843660,0.170530,0.079556,0.839414,0.672043,0.778358,0.859180,1.000000,0.764014,0.737729,0.780570,0.387752,0.479161,0.660001,0.845373,0.776864
avg_dist_3_mall_m,0.730469,0.770401,0.448184,0.742400,0.590337,0.576057,0.531833,0.678219,0.775442,0.678272,0.672441,0.846587,0.693363,0.634791,0.821685,0.698570,0.267538,0.167485,0.811192,0.588349,0.663876,0.841073,0.764014,1.000000,0.735398,0.772013,0.404073,0.523242,0.595583,0.756090,0.793184
avg_dist_3_petstore_m,0.808409,0.808801,0.436780,0.724510,0.510498,0.510423,0.560630,0.642460,0.769971,0.744872,0.685203,0.807094,0.677710,0.480462,0.751802,0.659730,0.316645,0.190605,0.723283,0.575919,0.616563,0.725988,0.737729,0.735398,1.000000,0.601135,0.185786,0.446945,0.579332,0.727375,0.630633
dist_1_police_station_m,0.606905,0.736655,0.317630,0.703816,0.654849,0.568985,0.449114,0.687048,0.738331,0.644523,0.675907,0.785886,0.664802,0.442111,0.798730,0.710488,0.301022,0.049541,0.789969,0.577797,0.631390,0.822670,0.780570,0.772013,0.601135,1.000000,0.434638,0.448209,0.541095,0.705584,0.792328
avg_dist_3_pool_m,0.298956,0.304186,-0.014471,0.257556,0.153307,0.193378,0.188239,0.276964,0.257621,0.189896,0.181375,0.349072,0.177336,0.236447,0.412576,0.218009,0.006880,-0.076169,0.431831,0.305398,0.338763,0.418832,0.387752,0.404073,0.185786,0.434638,1.000000,0.163125,0.470383,0.250830,0.439822
avg_dist_3_recycling_point_m,0.536953,0.629156,0.599051,0.529450,0.540839,0.484220,0.588631,0.577552,0.620390,0.626104,0.574906,0.550768,0.685371,0.558722,0.546587,0.496100,0.275210,0.193037,0.497165,0.580926,0.538408,0.586466,0.479161,0.523242,0.446945,0.448209,0.163125,1.000000,0.542625,0.597290,0.397144
avg_dist_3_transport_station_entrance_m,0.746815,0.688806,0.421309,0.656634,0.597413,0.574130,0.542150,0.515255,0.715967,0.580488,0.479765,0.651569,0.661574,0.521577,0.819978,0.555082,0.159291,0.086446,0.715612,0.539600,0.561237,0.682312,0.660001,0.595583,0.579332,0.541095,0.470383,0.542625,1.000000,0.643033,0.549628
avg_dist_3_veterinary_clinic_m,0.706294,0.792981,0.494536,0.815028,0.704728,0.681489,0.583040,0.700321,0.842567,0.729848,0.751030,0.796581,0.770765,0.402720,0.793989,0.843465,0.232808,0.149562,0.769096,0.613267,0.697056,0.841859,0.845373,0.756090,0.727375,0.705584,0.250830,0.597290,0.643033,1.000000,0.790998
avg_dist_3_vocational_school_m,0.581015,0.646980,0.307652,0.663519,0.555848,0.521624,0.435338,0.620826,0.673619,0.585865,0.649585,0.754413,0.622173,0.355849,0.731163,0.714929,0.176117,0.022417,0.736957,0.510525,0.566132,0.806280,0.776864,0.793184,0.630633,0.792328,0.439822,0.397144,0.549628,0.790998,1.000000

## Extracting strongest correlation pairs

While full correlation matrices are useful for broad exploration, they can become difficult to read when working with many engineered features.

To improve interpretability, the next step converts each correlation matrix into a **long-format table of the strongest correlation pairs**.

This process:

- reshapes the correlation matrix into pairwise rows
- removes self-correlations  
  (a feature correlated with itself)
- removes duplicated mirrored pairs  
  (for example A–B and B–A)
- keeps only correlations above a chosen threshold
- sorts results from strongest to weakest

This allows us to focus on the most meaningful relationships within each feature family.

---

### Correlation thresholds

Different thresholds are used depending on the feature group:

- **spatial features:** 0.7  
  strong co-location patterns

- **population-normalized features:** 0.4  
  fewer variables and typically weaker expected relationships

- **distance features:** 0.7  
  strong accessibility clusters

These tables provide a much clearer basis for interpretation than scanning the full matrices.

They help identify:

- functional urban clusters
- co-accessibility patterns
- residential service relationships
- potential redundant features for modeling

In [25]:
def get_top_correlations(corr_matrix, min_corr=0.7):
    corr_long = (
        corr_matrix
        .stack()
        .reset_index()
    )

    corr_long.columns = ["feature_1", "feature_2", "correlation"]

    corr_long = corr_long[
        corr_long["feature_1"] != corr_long["feature_2"]
    ]

    corr_long["pair_key"] = corr_long.apply(
        lambda x: tuple(sorted([x["feature_1"], x["feature_2"]])),
        axis=1
    )

    corr_long = corr_long.drop_duplicates("pair_key")

    corr_long = corr_long[
        corr_long["correlation"].abs() >= min_corr
    ].sort_values("correlation", ascending=False)

    return corr_long.drop(columns="pair_key")

In [26]:
top_spatial = get_top_correlations(corr_spatial)
top_population = get_top_correlations(corr_population, min_corr=0.4)
top_distance = get_top_correlations(corr_distance)

display(top_spatial.head(30))
display(top_population.head(30))
display(top_distance.head(30))

,feature_1,feature_2,correlation
518,gas_station_count_per_sq_km,gas_station_electric_count_per_sq_km,0.988443
143,dental_office_count_per_sq_km,doctor_count_per_sq_km,0.967675
1092,pharmacy_count_per_sq_km,supermarket_count_per_sq_km,0.945503
1650,theater_count_per_sq_km,venue_count_per_sq_km,0.920259
1458,social_club_count_per_sq_km,spaeti_count_per_sq_km,0.909688
724,kindergarten_count_per_sq_km,supermarket_count_per_sq_km,0.905527
474,gallery_count_per_sq_km,hotel_count_per_sq_km,0.897039
500,gallery_count_per_sq_km,venue_count_per_sq_km,0.892896
479,gallery_count_per_sq_km,museum_count_per_sq_km,0.886656
495,gallery_count_per_sq_km,theater_count_per_sq_km,0.875516
684,hotel_count_per_sq_km,venue_count_per_sq_km,0.874728
713,kindergarten_count_per_sq_km,pharmacy_count_per_sq_km,0.873758
127,cinema_count_per_sq_km,theater_count_per_sq_km,0.870517
1008,parking_capacity_per_sq_km,bike_lane_length_m_per_sq_km,0.865955
989,parking_capacity_per_sq_km,pharmacy_count_per_sq_km,0.864686
1648,theater_count_per_sq_km,transport_station_entrance_count_per_sq_km,0.859472
1512,spaeti_count_per_sq_km,venue_count_per_sq_km,0.859267
988,parking_capacity_per_sq_km,parking_space_count_per_sq_km,0.858465
1000,parking_capacity_per_sq_km,supermarket_count_per_sq_km,0.856874
1466,social_club_count_per_sq_km,venue_count_per_sq_km,0.841684
1788,transport_station_entrance_count_per_sq_km,venue_count_per_sq_km,0.841577
1085,pharmacy_count_per_sq_km,religious_institution_count_per_sq_km,0.839449
721,kindergarten_count_per_sq_km,social_club_count_per_sq_km,0.838431
717,kindergarten_count_per_sq_km,religious_institution_count_per_sq_km,0.837783
153,dental_office_count_per_sq_km,kindergarten_count_per_sq_km,0.837720
1460,social_club_count_per_sq_km,supermarket_count_per_sq_km,0.836073
245,doctor_count_per_sq_km,kindergarten_count_per_sq_km,0.828426
587,gas_station_electric_count_per_sq_km,theater_count_per_sq_km,0.826170
132,cinema_count_per_sq_km,venue_count_per_sq_km,0.823378
583,gas_station_electric_count_per_sq_km,social_club_count_per_sq_km,0.822531

                     feature_1              feature_2  correlation
1  kindergarten_count_per_1000  school_count_per_1000     0.568598

,feature_1,feature_2,correlation
39,avg_dist_5_bakery_m,avg_dist_5_pharmacy_m,0.919639
609,avg_dist_3_gas_station_m,avg_dist_3_gas_station_electric_m,0.913125
260,avg_dist_5_pharmacy_m,avg_dist_5_supermarket_m,0.903750
101,avg_dist_3_dental_office_m,avg_dist_5_pharmacy_m,0.900262
34,avg_dist_5_bakery_m,avg_dist_3_dental_office_m,0.887182
355,avg_dist_5_spaeti_m,avg_dist_5_transport_station_m,0.881571
291,avg_dist_3_playground_m,avg_dist_5_supermarket_m,0.878610
452,avg_dist_5_transport_station_m,avg_dist_3_food_market_m,0.876308
40,avg_dist_5_bakery_m,avg_dist_3_playground_m,0.874769
262,avg_dist_5_pharmacy_m,avg_dist_5_transport_station_m,0.870161
43,avg_dist_5_bakery_m,avg_dist_5_supermarket_m,0.869094
362,avg_dist_5_spaeti_m,avg_dist_3_government_office_m,0.865147
455,avg_dist_5_transport_station_m,avg_dist_3_government_office_m,0.865109
263,avg_dist_5_pharmacy_m,avg_dist_3_bank_m,0.864074
108,avg_dist_3_dental_office_m,avg_dist_3_bank_m,0.864020
1,avg_dist_5_atm_m,avg_dist_5_bakery_m,0.862774
14,avg_dist_5_atm_m,avg_dist_5_transport_station_m,0.862313
45,avg_dist_5_bakery_m,avg_dist_5_transport_station_m,0.859254
673,avg_dist_3_government_office_m,avg_dist_3_library_m,0.859180
105,avg_dist_3_dental_office_m,avg_dist_5_supermarket_m,0.847491
364,avg_dist_5_spaeti_m,avg_dist_3_mall_m,0.846587
711,avg_dist_3_library_m,avg_dist_3_veterinary_clinic_m,0.845373
42,avg_dist_5_bakery_m,avg_dist_5_spaeti_m,0.843779
487,avg_dist_3_bank_m,avg_dist_3_library_m,0.843660
494,avg_dist_3_bank_m,avg_dist_3_veterinary_clinic_m,0.843465
270,avg_dist_5_pharmacy_m,avg_dist_3_library_m,0.842795
456,avg_dist_5_transport_station_m,avg_dist_3_library_m,0.842641
277,avg_dist_5_pharmacy_m,avg_dist_3_veterinary_clinic_m,0.842567
680,avg_dist_3_government_office_m,avg_dist_3_veterinary_clinic_m,0.841859
674,avg_dist_3_government_office_m,avg_dist_3_mall_m,0.841073

## Export final exploration dataset

The cleaned feature table is now exported as a CSV file for downstream tasks such as:

- exploratory analysis
- clustering
- feature selection
- machine learning modeling

This exported dataset contains only the final engineered features and excludes redundant raw variables.

In [27]:
final_output_path = Path("../data/neighborhood_features_exploration.csv")
df_model.to_csv(final_output_path, index=False)
print(f"Saved final exploration table to: {final_output_path}")

Saved final exploration table to: ../data/neighborhood_features_exploration.csv

## Feature engineering logic

Feature transformations follow four principles:

- **raw counts** for initial inspection
- **population density** for resident-facing amenities
- **spatial density** for point-based infrastructure and activity layers
- **area share** for land-use signals such as parks and playgrounds
- **proximity features** based on centroid-to-amenity distance, using different values of k depending on amenity frequency

This keeps the feature space interpretable while preparing it for later clustering and neighborhood-type discovery.